package sql

object Crs extends App{
//  val csr = List("CRS_CUSTOMERS_TO_ACCOUNTS","UNIFIED_ALERTS","ALERTED_CUSTOMERS",
//    "CRS_3_LINKED_CUSTOMERS","CRS_CUSTOMERS","TRANSACTIONS","ALERTED_CUSTOMERS","CRS_CUSTOMERS_TO_ACCOUNTS",
//    "CRS_CUSTOMER","ALERTED_CUSTOMERS","ALERTED_CUSTOMERS","CRS_CUSTOMERS","CUSTOMER_OCCUPATION_BUSINESS","ALERTED_CUSTOMERS","CRS_CUSTOMERS_TO_ACCOUNTS","UNIFIED_ALERTS","CRS_CUSTOMER_HISTORY","CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS","CRS_CUSTOMERS_TO_ACCOUNTS","CUSTOMER_OCCUPATION_BUSINESS","TRANSACTIONS","ALERTED_CUSTOMERS","UNIFIED_ALERTS","CUSTOMER_OCCUPATION_BUSINESS","CRS_CUSTOMER_HISTORY","ALERTED_CUSTOMERS","CUSTOMER_OCCUPATION_BUSINESS","CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS","CRS_COMPONENT_RISK_SCORE","ALERTED_CUSTOMERS","CRS_CUSTOMER_HISTORY","TRANSACTIONS","CRS_CUSTOMERS","CRS_CUSTOMERS_TO_ACCOUNTS")
//  val csr2 = csr.distinct
//  //println(csr2)
//  val x = List(csr2).distinct
//  //println(x)
//  val x1 = 40 + 20 + 17 + 22 + 48 + 6  + 4 + 1 + 5 + 2
//  //println(x1)
//  val X2  = 27 + 27 + 5
//    val ts = List("TRANSACTIONS","UNIFIED_ALERTS","NS_HITS","ALERTED_CUSTOMERS","NS_HITS","UNIFIED_ALERTS","NS_HITS","UNIFIED_ALERTS","TRANSACTIONS","NS_ITS","NS_HITS","TM_IAD_MODEL_THRESHOLD")
//    val ts2 = ts.distinct
//
//
//
//  val ns = List("UNIFIED_ALERTS","NS_HITS","NS_ITS","TM_IAD_MODEL_THRESHOLD","NS_HITS")
//  val ns2 = ns.distinct
//  println(ns2)

  val x = List("CRS_CUSTOMERS_TO_ACCOUNTS","CDD_ALERTS","LOAN_CUSTOMERS","ALERTED_CUSTOMERS","UNIFIED_ALERTS","TRANSACTIONS","TRANSACTIONS","UNIFIED_ALERTS","TRANSACTIONS","ALERTED_CUSTOMERS","LOAN_CUSTOMERS","ALERTED_CUSTOMERS_TO_ACCOUNTS","ALERTED_CUSTOMERS","UNIFIED_ALERTS","ALERTED_CUSTOMERS_TO_ACCOUNTS","UNIFIED_ALERTS","")

}
