id: String,
  partyKey: Option[String] = None,
  transactionDate: Option[Timestamp] = None,
  productCode: Option[String] = None,
  accountCurrency: Option[String] = None,
  amount: Option[Double] = None,
  transactionCurrency: Option[String] = None,
  transactionCurrencyAmount: Option[Double] = None,
  localCurrencyEquivalent: Option[Double] = None,
  isCredit: Option[Boolean] = None,
  accountId: Option[String] = None,
  transactionTypeCode: Option[String] = None,
  transactionTypeDescription: Option[String] = None,
  beneficiary: Option[String] = None,
  originatorAddress: Option[String] = None,
  originatorBankCountryCode: Option[String] = None,
  beneficiaryAddress: Option[String] = None,
  beneficiaryBankCountryCode: Option[String] = None,
  remittanceCountry: Option[String] = None,
  remittancePaymentDetails: Option[String] = None,
  chequeNo: Option[String] = None,
  tellerId: Option[String] = None,
  yourReference: Option[String] = None,
  ourReference: Option[String] = None,
  bankInfo: Option[String] = None,
  countryOfTransaction: Option[String] = None,
  mcc: Option[String] = None,
  merchantName: Option[String] = None,
  originator: Option[String],
  atmId: Option[String],
  atmLocation: Option[String],
  counterParty: Option[String],
  swiftMsgType: Option[String],
  swiftMsgInfo: Option[String],
  tdNumber: Option[String],
  trancheNo: Option[String],
  creditCardNumber: Option[String],
  mccMerchantName: String,
  highRiskCountryFlag: Option[Boolean],
  instrument: Option[String],
  sourceOfFunds: Option[String],
  sourceRiskFlag: Option[Boolean],
  destinationOfFunds: Option[String],
  destinationRiskFlag: Option[Boolean],
  beneficiaryType: Option[String],
  c2cLinkageFlag: Option[Boolean],
  beneficiaryAdverseFlag: Option[Boolean],
  beneficialBankName: Option[String],
  originatorBankName: Option[String],
  oppAccountNumber: Option[String],
  bankBranchCode: Option[String],
  transactionPurpose: Option[String],
  partyCountryRiskLevel: Option[String] = None,
  oppCountryRiskLevel: Option[String] = None,
  sourceOfTxnFunds: Option[String],
  oppCitizenshipCountry: Option[String],
  counterpartyType: Option[String],
  refundToThirdPartyFlag: Option[String],
  ipRiskiness: Option[String]