//case class CrsCustomers(
//                         customerKey: Option[String],
//                         customerName: Option[String] ,
//                         dateOfBirthIncorporation: Option[String] ,
//                         customerOnboardDate: Option[Timestamp] ,
//                         customerType: Option[String],
//                         customerIndustry: Option[String],
//                         customerStatus: Option[String],
//                         kycReviewDate: Option[Timestamp],
//                         division: Option[String],
//                         typeOfBusiness: Option[String],
//                         residentialAddress: Option[String],
//                         postalCode: Option[String],
//                         contactNumber: Option[String],
//                         designation: Option[String],
//                         gender: Option[String],
//                         nationality: Option[String],
//                         idNumber: Option[String],
//                         idType: Option[String],
//                         idCountry: Option[String],
//                         employerName: Option[String],
//                         pepInd: Option[Boolean],
//                         bankStaffIndicator: Option[Boolean],
//                         highRiskPartyInfo: Option[String],
//                         annualTurnover: Option[Double],
//                         birthIncorporationCountry: Option[String],
//                         residenceOperationCountry: Option[String],
//                         alertId: Option[String],
//                         alertDate: Option[Timestamp],
//                         aum: Option[Double],
//                         amlBusiness: Option[String],
//                         secondaryAmlBusiness: Option[String],
//                         annualRevenueOrIncome: Option[Double],
//                         tptMajorBuyerName: Option[String],
//                         tptMajorSupplierName: Option[String],
//                         tptCoreParticipantToLoanName: Option[String],
//                         sowEmployerName: Option[String],
//                         sowBusinessOwnershipCompanyName: Option[String],
//                         sowInheritanceGiftsProviderName: Option[String],
//                         sowInvestmentType: Option[String],
//                         sowRentalReceiptPropertyType: Option[String],
//                         sofCashCashChequeProviderName: Option[String],
//                         sof3rdPartyChequeProviderName: Option[String],
//                         sofNonCashChequeCashierOrderBankDraftProviderName: Option[String],
//                         sofSamePartyInternetBankOrInternalTrfProviderName: Option[String],
//                         sof3rdPartyInternetBankOrInternalTrfProviderName: Option[String],
//                         sof3rdPartyRemittanceProviderName: Option[String],
//                         pepFlag: Option[Boolean],
//                         adverseNewsFlag: Option[Boolean],
//                         sanctionFlag: Option[Boolean],
//                         incompleteCddFlag: Option[Boolean],
//                         paidUpCapital: Option[Double],
//                         nonPhysicalAddressFlag: Option[Boolean],
//                         shareholderBoOutsideFlag: Option[Boolean],
//                         soleDirectorFlag: Option[Boolean],
//                         singleAcctOperateFlag: Option[Boolean],
//                         underlyingBuzTaxFlag: Option[Boolean],
//                         complexStructure: Option[String],
//                         taxHavenFlag: Option[Boolean],
//                         alertBuType: Option[String],
//                         relationshipMgrId: Option[String],
//                         populationCode: Option[String],
//                         acquisitionDate: Option[Timestamp],
//                         methodOfOpening: Option[String],
//                         statusCode: Option[String],
//                         stockExchangeList: Option[String],
//                         wholesaleBanknoteFlag: Option[Boolean],
//                         parentHighRiskFlag: Option[Boolean],
//                         race: Option[String],
//                         maritalStatus: Option[String],
//                         employmentStatus: Option[String],
//                         domesticPepFlag: Option[Boolean],
//                         foreignPepFlag: Option[Boolean],
//                         domesticRcaFlag: Option[Boolean],
//                         foreignRcaFlag: Option[Boolean],
//                         channel: Option[String],
//                         occupation: Option[String],
//                         kycMailingAddress: Option[String],
//                         selfDiscoveredPepOrRca: Option[Boolean],
//                         additionalIdCitizenship: Option[String],
//                         watchlistFlag: Option[Boolean],
//                         entityType: Option[String],
//                         entityTypeDesc: Option[String],
//                         idExpiryDate: Option[Timestamp],
//                         residenceFlag: Option[Boolean],
//                         natureOfBusiness: Option[String],
//                         weakAmlCtrlFlag: Option[Boolean],
//                         amlViolationEnforcementFlag: Option[Boolean]
//                       )
//
//case class CrsCustomersToAccounts (
//                                    partyKey : Option[String],
//                                    accountId: Option[String],
//                                    productId : Option[String],
//                                    alertId : Option[String],
//                                    accountKey : Option[String],
//                                    c2aRelationShip : Option[String],
//                                    product : Option[String],
//                                    openDate  : Option[Timestamp],
//                                    balance : Option[Double],
//                                    creditLimit: Option[Double],
//                                    cardNumber : Option[String],
//                                    accountName : Option[String],
//                                    accountClosedDate : Option[Timestamp],
//                                    accountStatus : Option[String],
//                                    accountCurrency : Option[String],
//                                    accountDrAvgBalance : Option[Double],
//                                    accountCrAvgBalance : Option[Double],
//                                    fdReceiptNumber : Option[String],
//                                    fdOriginalAmount : Option[Double],
//                                    fdPlacementDate : Option[Timestamp],
//                                    fdMaturityDate  : Option[Timestamp],
//                                    fdWithdrawalDate  : Option[Timestamp],
//                                    outstandingLoanBalance : Option[Double],
//                                    loanAmount  : Option[Double],
//                                    loanInstallmentAmount  : Option[Double],
//                                    loanGroup : Option[String],
//                                    loanType : Option[String],
//                                    loanPurposeCode : Option[String],
//                                    loanGlGroup  : Option[String],
//                                    loanDisbursementDate  : Option[Timestamp],
//                                    loanMaturityDate  : Option[Timestamp],
//                                    totalRepaidAmount : Option[Double],
//                                    numberOfRepayments  : Option[Int],
//                                    createdTimestamp  : Option[Timestamp],
//                                    createdUser : Option[String],
//                                    updatedTimestamp : Option[Timestamp],
//                                    updatedUser  : Option[String],
//                                    ttUpdatedTime  : Option[Timestamp],
//                                    alertDate  : Option[Timestamp],
//                                    typeCode : Option[String],
//                                    accountDescription : Option[String],
//                                    currencyCode : Option[String],
//                                    outstandingFdBalance  : Option[Double],
//                                    purposeOfOpening : Option[String],
//                                    kycDeclaredMonthlyIncomingVol : Option[Int],
//                                    kycDeclaredMonthlyIncomingAmount : Option[Double],
//                                    kycDeclaredMonthlyOutgoingVol : Option[Int],
//                                    kycDeclaredMonthlyOutgoingAmount : Option[Double],
//                                    anticipatedMonthlyVolumeMisc: Option[Int]
//                                  )
//
//case class CustomerOccupationBusiness(
//                                       customerKey : Option[String],
//                                       alertId  : Option[String],
//                                       occupationBusiness : Option[String],
//                                       occupationBusinessStartDate : Option[Timestamp],
//                                       occupationBusinessEndDate : Option[Timestamp],
//                                       statusCode : Option[String],
//                                       employmentBusinessStatus : Option[String],
//                                       masIndustryCode : Option[String],
//                                       regionsOrCountryOfOperation : Option[String],
//                                       alertDate :Option[Timestamp]
//                                     )
//
//case class CrsCustomerHistory(
//                               customerKey: Option[String],
//                               crsCreateDate: Timestamp,
//                               ctbClusterId: String,
//                               ctbModelId: String,
//                               overallRiskScore: Option[Double],
//                               kycRiskScore: Option[Double] = None,
//                               screeningRiskScore: Option[Double] = None,
//                               networkRiskScore: Option[Double],
//                               transactionBehaviourScore: Option[Double] = None,
//                               riskShiftReason: Option[String] = None,
//                               segmentCode: Option[String],
//                               productName: Option[String] = None,
//                               strCount: Option[Int] = None,
//                               previousRiskLevel: Option[String] = None,
//                               currentMlSuggestedRiskLevel: Option[String] = None,
//                               currentRiskLevel: Option[String] = None,
//                               notes: Option[String] = None,
//                               isReviewed: Option[Boolean] = None,
//                               versionColumn: Option[Double] = None,
//                               nrFlag: Option[Boolean] = None,
//                               segmentName: Option[String] = None,
//                               clusterSize: Option[Int] = None,
//                               severityScore: Option[Double] = None,
//                               yieldRate: Option[Double] = None,
//                               clusterSegmentAttributes: Option[String] = None,
//                               kycRiskLevel: Option[String] = None,
//                               alertId: Option[String] = None,
//                               totalAum: Option[Double] = None
//                             )
//
//case class CrsAlertedCustomersLinkedCustomers(
//                                               primaryPartyKey: String,
//                                               linkedPartyKey: String,
//                                               partyName: Option[String],
//                                               riskRating: Option[String],
//                                               occupation: Option[String],
//                                               segment: Option[String],
//                                               nationality: Option[String],
//                                               dobOrIncorporationDate: Option[Timestamp],
//                                               relationType: Option[String],
//                                               relationDescription: Option[String],
//                                               shareholderPercentage: Option[String],
//                                               isStaff: Option[Boolean],
//                                               segmentCode: Option[String],
//                                               maskApplied: Option[Boolean],
//                                               alertId: Option[String],
//                                               alertDate: Option[Timestamp],
//                                               sanctionFlag: Option[Boolean],
//                                               adverseNewsFlag: Option[Boolean],
//                                               domesticPepFlag: Option[Boolean],
//                                               foreignPepFlag: Option[Boolean],
//                                               domesticRcaFlag: Option[Boolean],
//                                               foreignRcaFlag: Option[Boolean],
//                                               pepFlag: Option[Boolean],
//                                               watchlistFlag: Option[Boolean],
//                                               relationshipStartDate: Option[Timestamp],
//                                               relationshipEndDate: Option[Timestamp]
//                                             )
//
//case class CrsComponentRiskScore (
//                                   customerKey : Option[String],
//                                   componentCreateTimestamp : Option[Timestamp],
//                                   crsComponent : Option[String],
//                                   riskScore : Option[Double],
//                                   riskShiftReason : Option[String],
//                                   componentAttributes : Option[String],
//                                   alertId:Option[String]
//                                 )
//
//case class Transactions(
//                         id: String,
//                         partyKey: Option[String] = None,
//                         transactionDate: Option[Timestamp] = None,
//                         productCode: Option[String] = None,
//                         accountCurrency: Option[String] = None,
//                         amount: Option[Double] = None,
//                         transactionCurrency: Option[String] = None,
//                         transactionCurrencyAmount: Option[Double] = None,
//                         localCurrencyEquivalent: Option[Double] = None,
//                         isCredit: Option[Boolean] = None,
//                         accountId: Option[String] = None,
//                         transactionTypeCode: Option[String] = None,
//                         transactionTypeDescription: Option[String] = None,
//                         beneficiary: Option[String] = None,
//                         originatorAddress: Option[String] = None,
//                         originatorBankCountryCode: Option[String] = None,
//                         beneficiaryAddress: Option[String] = None,
//                         beneficiaryBankCountryCode: Option[String] = None,
//                         remittanceCountry: Option[String] = None,
//                         remittancePaymentDetails: Option[String] = None,
//                         chequeNo: Option[String] = None,
//                         tellerId: Option[String] = None,
//                         yourReference: Option[String] = None,
//                         ourReference: Option[String] = None,
//                         bankInfo: Option[String] = None,
//                         countryOfTransaction: Option[String] = None,
//                         mcc: Option[String] = None,
//                         merchantName: Option[String] = None,
//                         originator: Option[String],
//                         atmId: Option[String],
//                         atmLocation: Option[String],
//                         counterParty: Option[String],
//                         swiftMsgType: Option[String],
//                         swiftMsgInfo: Option[String],
//                         tdNumber: Option[String],
//                         trancheNo: Option[String],
//                         creditCardNumber: Option[String],
//                         highRiskCountryFlag: Option[Boolean],
//                         instrument: Option[String],
//                         sourceOfFunds: Option[String],
//                         sourceRiskFlag: Option[Boolean],
//                         destinationOfFunds: Option[String],
//                         destinationRiskFlag: Option[Boolean],
//                         beneficiaryType: Option[String],
//                         c2cLinkageFlag: Option[Boolean],
//                         beneficiaryAdverseFlag: Option[Boolean],
//                         originatorBankName: Option[String],
//                         oppAccountNumber: Option[String],
//                         bankBranchCode: Option[String],
//                         transactionPurpose: Option[String],
//                         partyCountryRiskLevel: Option[String] = None,
//                         oppCountryRiskLevel: Option[String] = None,
//                         counterPartyNationality:Option[String],
//                         sourceOfTxnFunds: Option[String],
//                         oppCitizenshipCountry: Option[String],
//                         counterPartyType: Option[String],
//                         refundToThirdPartyFlag: Option[String],
//                         ipRiskiness: Option[String],
//                         counterpartyType:Option[String],
//                         alertId:Option[String]
//                       )
//
//                       alertId: String,
//                          alertSourceId: String,
//                          alertDate: Option[Date],
//                          alertQuality: Option[String] = None,
//                          referenceDate: Option[Timestamp] = None,
//                          primaryPartyKey: Option[String] = None,
//                          primaryPartyName: Option[String] = None,
//                          alertStatus: Option[Int] = None,
//                          rules: Option[String] = None,
//                          alertLevel: Option[String] = None,
//                          alertScore: Option[Double] = None,
//                          segmentName: Option[String] = None,
//                          segmentCode: Option[String] = None,
//                          accountId: Option[String] = None,
//                          accountCurrency: Option[String] = None,
//                          accountType: Option[String] = None,
//                          accountOpenDate: Option[Timestamp] = None,
//                          hitsScore: Option[Double] = None,
//                          alertAge: Option[Int] = None,
//                          clusterId: Option[String] = None,
//                          modelId: Option[Int] = None,
//                          clusterScore: Option[Double] = None,
//                          analystName: Option[String] = None,
//                          closureDate: Option[Timestamp] = None,
//                          investigationResult: Option[String] = None,
//                          isStr: Option[Boolean] = None,
//                          isIssue: Option[Int] = None,
//                          isStaff: Option[Boolean] = None,
//                          investigatorNote: Option[String] = None,
//                          supervisorNote: Option[String] = None,
//                          nextActions: Option[String] = None,
//                          reopenDate: Option[Timestamp] = None,
//                          attachmentId: Option[String] = None,
//                          attachmentName: Option[String] = None,
//                          predictionDate: Option[Timestamp] = None,
//                          isWhitelisted: Option[Boolean] = None,
//                          partyType: Option[String] = None,
//                          partyOrgUnit: Option[String] = None,
//                          partyRace: Option[String] = None,
//                          partyDob: Option[Timestamp] = None,
//                          partyAddress: Option[String] = None,
//                          partyIdType: Option[String] = None,
//                          partyIdNo: Option[String] = None,
//                          partyIdCountry: Option[String] = None,
//                          partyAliases: Option[String] = None,
//                          partyGender: Option[String] = None,
//                          partyAge: Option[Int] = None,
//                          partyNationality: Option[String] = None,
//                          partyBirthCountry: Option[String] = None,
//                          partyResidenceCountry: Option[String] = None,
//                          partyBusinessType: Option[String] = None,
//                          partyCrsRiskScore: Option[Double] = None,
//                          hitsSummary: Option[String] = None,
//                          createdTimestamp: Option[Timestamp] = None,
//                          updatedTimestamp: Option[Timestamp] = None,
//                          createdUser: Option[String] = None,
//                          updatedUser: Option[String] = None,
//                          runInstanceExecutionId: Option[String] = None,
//                          triggeredTypologies: Option[String] = None,
//                          actionableInsights: Option[String] = None,
//                          pipelineId: Option[Int] = None,
//                          pipelineInstanceId: Option[Int] = None,
//                          scenarioName: Option[String] = None,
//                          scenarioId: Option[String] = None,
//                          entityCount: Option[Int] = None,
//                          transactionKey: Option[String] = None,
//                          txnDateTime: Option[Timestamp] = None,
//                          swiftMsgType: Option[String] = None,
//                          msgDirection: Option[String] = None,
//                          accountNumber: Option[String] = None,
//                          txnAmount: Option[Double] = None,
//                          txnDirection: Option[String] = None,
//                          origAccountNo: Option[String] = None,
//                          oppAccountNo: Option[String] = None,
//                          origCurrencyCode: Option[String] = None,
//                          oppCurrencyCode: Option[String] = None,
//                          origTxnAmount: Option[Double] = None,
//                          untriggeredAccountId: Option[String] = None,
//                          idExpiryDate: Option[Timestamp] = None,
//                          predictOffence: Option[String] = None,
//                          alertType: Option[Int] = None,
//                          typologyTechnique: Option[String] = None,
//                          organisationUnit: Option[String] = None,
//                          alertChangeFrom: Option[String] = None,
//                          typeOfAlert: Option[String] = None,
//                          alertTotalHits: Option[Int] = None,
//                          rawPartyName: Option[String] = None,
//                          yearsInCorp: Option[Long] = None,
//                          yearOfIncorporation: Option[Long] = None,
//                          customerLocation: Option[String] = None,
//                          occupation: Option[String] = None,
//                          entityTypeDescription: Option[String] = None,
//                          businessSegment: Option[String] = None,
//                          buyerSellerName: Option[String] = None,
//                          buyerSellerIncorporationCountry: Option[String] = None,
//                          countryOfIncorporation: Option[String] = None,
//                          relatedPartyNames: Option[String] = None,
//                          buyerSellerFlag: Option[Int] = None,
//                          customerNumberOfTokens: Option[Long] = None,
//                          clusterVersion: Option[String] = None,
//                          alertKycScore: Option[Double] = None,
//                          customerCountryOfOperation: Option[String] = None,
//                          customerSegment: Option[String] = None,
//                          nsAlertReasonDesc: Option[String] = None,
//                          nsAlertComment: Option[String] = None,
//                          analystFullName: Option[String] = None,
//                          expectedCloseDate: Option[Timestamp] = None,
//                          alertProcessedHits: Option[Long] = None,
//                          sourceOfFunds: Option[String] = None,
//                          sourceOfTxnFunds: Option[String] = None,
//                          additionalInfo: Option[String] = None,
//                          referenceNumber: Option[String] = None,
//                          transactionTypeCode: Option[String] = None,
//                          transactionTypeDescription: Option[String] = None,
//                          oppTxnAmount: Option[Double] = None,
//                          triggeredTypologyIds: Option[String] = None,
//                          triggeredTypologyNames: Option[String] = None,
//                          txnCurrency: Option[String] = None,
//                          triggeredRules: Option[String] = None,
//                          triggeredRulesActionSummary: Option[String] = None,
//                          triggeredRulesEntitySummary: Option[String] = None
//                        )