Insert into disp_common_fields 
(product_name,table_name,field_name,field_label,field_type,source_db) Values
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_CLOSED_DATE','Account Closed Date','date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_CR_AVG_BALANCE','Account Cr Avg Balance','number','Hbase'),
('CRS','UNIFIED_ALERTS','ACCOUNT_CURRENCY','Account Currency','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_DESCRIPTION','Account Description','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_DR_AVG_BALANCE','Account Dr Avg Balance','number','Hbase'),
('CRS','UNIFIED_ALERTS','ACCOUNT_ID','Account Id','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_NAME','Account Name','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_STATUS','Account Status','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACQUISITION_DATE','Acquisition Date','date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ADDITIONAL_ID_CITIZENSHIP','Additional Id Citizenship','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','ADVERSE_NEWS_FLAG','Adverse News Flag','boolean','Hbase'),
('CRS','UNIFIED_ALERTS','ALERT_AGE','Alert Age','text','Hbase'),
('CRS','CRS_CUSTOMERS','ALERT_BU_TYPE','Alert Bu Type','text','Hbase'),
('CRS','UNIFIED_ALERTS','ALERT_DATE','Alert Date','Date','Hbase'),
('CRS','UNIFIED_ALERTS','ALERT_ID','Alert Id','text','Hbase'),
('CRS','UNIFIED_ALERTS','ALERT_LEVEL','Alert Level','text','Hbase'),
('CRS','UNIFIED_ALERTS','ALERT_TYPE','Alert Type','number','Hbase'),
('CRS','CRS_CUSTOMERS','AML_BUSINESS','Aml Business','text','Hbase'),
('CRS','CRS_CUSTOMERS','AML_VIOLATION_ENFORCEMENT_FLAG','Aml Violation Enforcement Flag','boolean','Hbase'),
('CRS','TRANSACTIONS','AMOUNT','Amount','number','Hbase'),
('CRS','ALERTED_CUSTOMERS','ANNUAL_REVENUE_OR_INCOME','Annual Revenue Or Income','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ANTICIPATED_MONTHLY_VOLUME_MISC','Anticipated Monthly Volume Misc','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','BALANCE','Balance','number','Hbase'),
('CRS','TRANSACTIONS','BANK_INFO','Bank Info','text','Hbase'),
('CRS','TRANSACTIONS','BENEFICIARY','Beneficiary','text','Hbase'),
('CRS','TRANSACTIONS','BENEFICIARY_BANK_COUNTRY_CODE','Beneficiary Bank Country Code','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','C2A_RELATIONSHIP','C2a Relationship','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','CARD_NUMBER','Card Number','text','Hbase'),
('CRS','CRS_CUSTOMERS','CHANNEL','Channel','text','Hbase'),
('CRS','TRANSACTIONS','CHEQUE_NO','Cheque No','text','Hbase'),
('CRS','UNIFIED_ALERTS','CLOSURE_DATE','Closure Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS','COMPLEX_STRUCTURE','Complex Structure','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','CONTACT_NUMBER','Contact Number','text','Hbase'),
('CRS','TRANSACTIONS','COUNTRY_OF_TRANSACTION','Country Of Transaction','text','Hbase'),
('CRS','TRANSACTIONS','CREDIT_CARD_NUMBER','Credit Card Number','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','CREDIT_LIMIT','Credit Limit','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','CURRENCY_CODE','Currency Code','text','Hbase'),
('CRS','CRS_CUSTOMERS','CUSTOMER_INDUSTRY','Customer Industry','text','Hbase'),
('CRS','CRS_CUSTOMERS','CUSTOMER_KEY','Customer Key','text','Hbase'),
('CRS','CRS_CUSTOMERS','CUSTOMER_NAME','Customer Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','CUSTOMER_ONBOARD_DATE','Customer Onboard Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS','CUSTOMER_STATUS','Customer Status','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','CUSTOMER_TYPE','Customer Type','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','DESIGNATION','Designation','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','DIVISION','Division','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','DOB_OR_INCORPORATION_DATE','Dob Or Incorporation Date','Date','Hbase'),
('CRS','ALERTED_CUSTOMERS','DOCUMENT_ID','Document Id','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','DOCUMENT_ISSUE_COUNTRY','Document Issue Country','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','DOCUMENT_TYPE','Document Type','text','Hbase'),
('CRS','CRS_CUSTOMERS','DOMESTIC_PEP_FLAG','Domestic Pep Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS','DOMESTIC_RCA_FLAG','Domestic Rca Flag','boolean','Hbase'),
('CRS','ALERTED_CUSTOMERS','EMPLOYER_NAME','Employer Name','text','Hbase'),
('CRS','CUSTOMER_OCCUPATION_BUSINESS','EMPLOYMENT_BUSINESS_STATUS','Employment Business status','text','Hbase'),
('CRS','CRS_CUSTOMERS','EMPLOYMENT_STATUS','Employment Status','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','ENTITY_TYPE_DESC','Entity Type Desc','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FD_MATURITY_DATE','Fd Maturity Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FD_ORIGINAL_AMOUNT','Fd Original Amount','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FD_PLACEMENT_DATE','Fd Placement Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FD_RECEIPT_NUMBER','Fd Receipt Number','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FD_WITHDRAWAL_DATE','Fd Withdrawal Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FOREIGN_PEP_FLAG','Foreign Pep Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FOREIGN_RCA_FLAG','Foreign Rca Flag','boolean','Hbase'),
('CRS','ALERTED_CUSTOMERS','GENDER','Gender','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','HIGH_RISK_PARTY_INFO','High Risk Party Info','text','Hbase'),
('CRS','UNIFIED_ALERTS','ID_EXPIRY_DATE','Id Expiry date','Date','Hbase'),
('CRS','CRS_CUSTOMERS','INCOMPLETE_CDD_FLAG','Incomplete Cdd Flag','boolean','Hbase'),
('CRS','TRANSACTIONS','IS_CREDIT','Is Credit','boolean','Hbase'),
('CRS','UNIFIED_ALERTS','IS_STAFF','Is Staff','boolean','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','KYC_DECLARED_MONTHLY_INCOMING_AMOUNT','Kyc Declared Monthly Incoming Amount','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','KYC_DECLARED_MONTHLY_INCOMING_VOL','Kyc Declared Monthly Incoming Vol','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','KYC_DECLARED_MONTHLY_OUTGOING_AMOUNT','Kyc Declared Monthly Outgoing Amount','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','KYC_DECLARED_MONTHLY_OUTGOING_VOL','Kyc Declared Monthly Outgoing Vol','number','Hbase'),
('CRS','ALERTED_CUSTOMERS','KYC_MAILING_ADDRESS','Kyc Mailing Address','text','Hbase'),
('CRS','CRS_CUSTOMERS','KYC_REVIEW_DATE','Kyc Review Date','Date','Hbase'),
('CRS','CRS_CUSTOMER_HISTORY','KYC_RISK_SCORE','Kyc Risk Score','number','Hbase'),
('CRS','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','LINKED_PARTY_KEY','Linked Party Key','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_AMOUNT','Loan Amount','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_DISBURSEMENT_DATE','Loan DisBurseMent Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_GL_GROUP','Loan Gl Group','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_GROUP','Loan Group','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_INSTALLMENT_AMOUNT','Loan Installment Amount','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_MATURITY_DATE','Loan Maturity Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_PURPOSE_CODE','Loan Purpose Code','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_TYPE','Loan Type','text','Hbase'),
('CRS','CRS_CUSTOMERS','MARITAL_STATUS','Marital Status','text','Hbase'),
('CRS','CUSTOMER_OCCUPATION_BUSINESS','MAS_INDUSTRY_CODE','Mas Industry Code','text','Hbase'),
('CRS','TRANSACTIONS','MERCHANT_NAME','Merchant Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','NATIONALITY','Nationality','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','NATURE_OF_BUSINESS','Nature Of Business','text','Hbase'),
('CRS','CRS_CUSTOMERS','NON_PHYSICAL_ADDRESS_FLAG','Non Physical Address Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','NUMBER_OF_REPAYMENTS','Number Of Repayments','number','Hbase'),
('CRS','UNIFIED_ALERTS','OCCUPATION','Occupation','text','Hbase'),
('CRS','CUSTOMER_OCCUPATION_BUSINESS','OCCUPATION_BUSINESS','Occupation Business','text','Hbase'),
('CRS','CUSTOMER_OCCUPATION_BUSINESS','OCCUPATION_BUSINESS_END_DATE','Occupation Business End Date','Date','Hbase'),
('CRS','CUSTOMER_OCCUPATION_BUSINESS','OCCUPATION_BUSINESS_START_DATE','Occupation Business Start Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','OPEN_DATE','Open Date','Date','Hbase'),
('CRS','TRANSACTIONS','ORIGINATOR','Originator','text','Hbase'),
('CRS','TRANSACTIONS','ORIGINATOR_BANK_COUNTRY_CODE','Originator Bank Country Code','text','Hbase'),
('CRS','TRANSACTIONS','OUR_REFERENCE','Our Reference','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','OUTSTANDING_FD_BALANCE','OutStanding fd balance','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','OUTSTANDING_LOAN_BALANCE','OutStanding Loan balance','number','Hbase'),
('CRS','CRS_CUSTOMER_HISTORY','OVERALL_RISK_SCORE','Overall Risk Score','number','Hbase'),
('CRS','CRS_CUSTOMERS','PAID_UP_CAPITAL','Paid Up Capital','number','Hbase'),
('CRS','CRS_CUSTOMERS','PARENT_HIGH_RISK_FLAG','Parent High Risk Flag','boolean','Hbase'),
('CRS','ALERTED_CUSTOMERS','PARTY_NAME','Party Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','PEP_FLAG','Pep Flag','Boolean','Hbase'),
('CRS','CRS_CUSTOMERS','PEP_IND','Pep Ind','Boolean','Hbase'),
('CRS','UNIFIED_ALERTS','POPULATION_CODE','Population Code','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','POSTAL_CODE','Postal Code','text','Hbase'),
('CRS','UNIFIED_ALERTS','PREDICTION_DATE','Prediction Date','Date','Hbase'),
('CRS','UNIFIED_ALERTS','PRIMARY_PARTY_KEY','Primary Party Key','text','Hbase'),
('CRS','CRS_CUSTOMER_HISTORY','PRODUCT_NAME','Product Name','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','PURPOSE_OF_OPENING','Purpose Of Opening','text','Hbase'),
('CRS','CRS_CUSTOMERS','RACE','Race','text','Hbase'),
('CRS','CUSTOMER_OCCUPATION_BUSINESS','REGIONS_OR_COUNTRY_OF_OPERATION','Regions Or Country Of Operation','text','Hbase'),
('CRS','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','RELATION_DESCRIPTION','Relation Description','text','Hbase'),
('CRS','CRS_CUSTOMERS','RELATIONSHIP_MGR_ID','RelationShip Mgr Id','text','Hbase'),
('CRS','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','RELATION_TYPE','Relation Type','text','Hbase'),
('CRS','CRS_CUSTOMERS','RESIDENCE_FLAG','Residence Flag','boolean','Hbase'),
('CRS','ALERTED_CUSTOMERS','RESIDENCE_OPERATION_COUNTRY','Residence Operation Country','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','RESIDENTIAL_ADDRESS','Residential Address','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','RISK_RATING','Risk Rating','text','Hbase'),
('CRS','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','RISK_RATING','Risk Rating','text','Hbase'),
('CRS','CRS_COMPONENT_RISK_SCORE','RISK_SHIFT','Risk Shift','text','Hbase'),
('CRS','CRS_CUSTOMERS','SANCTION_FLAG','Sanction Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS','SECONDARY_AML_BUSINESS','Secondary Aml Business','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','SEGMENT','Segment','text','Hbase'),
('CRS','UNIFIED_ALERTS','SEGMENT_CODE','Segment Code','text','Hbase'),
('CRS','UNIFIED_ALERTS','SEGMENT_NAME','Segment Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SELF_DISCOVERED_PEP_OR_RCA','Self Discovered Pep Or Rca','boolean','Hbase'),
('CRS','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','SHAREHOLDER_PERCENTAGE','ShareHolder Percentage','text','Hbase'),
('CRS','CRS_CUSTOMERS','SHAREHOLDER_BO_OUTSIDE_FLAG','Shareholder Bo Outside Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS','SINGLE_ACCT_OPERATE_FLAG','Single Acct Operate Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS','SOF_3RD_PARTY_CHEQUE_PROVIDER_NAME','Sof 3rd Party Cheque Provider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOF_3RD_PARTY_INTERNET_BANK_OR_INTERNAL_TRF_PROVIDER_NAME','Sof 3rd Party Internet Bank Or  Internal Trf Provider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOF_3RD_PARTY_REMITTANCE_PROVIDER_NAME','Sof 3rd Party Remittance ProVider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOF_CASH_CASH_CHEQUE_PROVIDER_NAME','Sof Cash Cash Cheque Provider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOF_NON_CASH_CHEQUE_CASHIER_ORDER_BANK_DRAFT_PROVIDER_NAME','Sof Non Cash Cheque Cashier Order Bank Draft Provider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOF_SAME_PARTY_INTERNET_BANK_OR_INTERNAL_TRF_PROVIDER_NAME','Sof Same Party Internet Bank Or Internal Trf Provider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOLE_DIRECTOR_FLAG','Sole Director Flag','boolean','Hbase'),
('CRS','UNIFIED_ALERTS','SOURCE_OF_FUNDS','Source Of Funds','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOW_BUSINESS_OWNERSHIP_COMPANY_NAME','Sow Business OwnerShip Company Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOW_EMPLOYER_NAME','Sow Employer Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOW_INHERITANCE_GIFTS_PROVIDER_NAME','Sow Inheritance Gifts Provider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOW_INVESTMENT_TYPE','Sow Investment Type','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOW_RENTAL_RECEIPT_PROPERTY_TYPE','Sow Rental Receipt Property Type','text','Hbase'),
('CRS','CRS_CUSTOMERS','STATUS_CODE','Status Code','text','Hbase'),
('CRS','CRS_CUSTOMERS','STOCK_EXCHANGE_LIST','Stock Exchange List','text','Hbase'),
('CRS','CRS_CUSTOMER_HISTORY','STR_COUNT','Str Count','number','Hbase'),
('CRS','CRS_CUSTOMERS','TAX_HAVEN_FLAG','Tax Haven Flag','boolean','Hbase'),
('CRS','TRANSACTIONS','TELLER_ID','Teller Id','text','Hbase'),
('CRS','CRS_CUSTOMERS','TOTAL_AUM','Total Aum','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','TOTAL_REPAID_AMOUNT','Total Repaid Amount','number','Hbase'),
('CRS','CRS_CUSTOMERS','TPT_CORE_PARTICIPANT_TO_LOAN_NAME','Tpt Core Participant To Loan Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','TPT_MAJOR_BUYER_NAME','Tpt Major Buyer Name','text','Hbase')
('CRS','CRS_CUSTOMERS','TPT_MAJOR_SUPPLIER_NAME','Tpt Major Supplier Name','text','Hbase')
('CRS','TRANSACTIONS','TRANCHE_NO','Tranche No','text','Hbase')
('CRS','TRANSACTIONS','TRANSACTION_CURRENCY','Transaction Currency','text','Hbase')
('CRS','TRANSACTIONS','TRANSACTION_CURRENCY_AMOUNT','Transaction Currency Amount','number','Hbase')
('CRS','TRANSACTIONS','TRANSACTION_DATE','Transaction Date','Date','Hbase')
('CRS','TRANSACTIONS','TRANSACTION_TYPE_CODE','Transaction Type Code','text','Hbase')
('CRS','TRANSACTIONS','TRANSACTION_TYPE_DESCRIPTION','Transaction Type Description','text','Hbase')
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','TYPE_CODE','Type Code','text','Hbase'),
('CRS','CRS_CUSTOMERS','UNDERLYING_BUZ_TAX_FLAG','Underlying Buz Tax Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS','WHOLESALE_BANKNOTE_FLAG','Wholesale Banknote Flag','boolean','Hbase'),
('CRS','TRANSACTIONS','YOUR_REFERENCE','Your Reference','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','AGE','Age','number','Hbase'),
('CRS','TRANSACTIONS','ID','Id','text','Hbase'),
('CRS','TRANSACTIONS','MCC','Mcc','text','Hbase');







Insert into disp_common_fields 
(product_name,table_name,field_name,field_label,field_type,source_db) Values
('NS','UNIFIED_ALERTS','ACCOUNT_ID','Account Id','text','Hbase'),
('NS','UNIFIED_ALERTS','ACCOUNT_TYPE','Account Type','text','Hbase'),
('NS','NS_HITS','ADDRESS_MATCH_SCORE','Address Match Score','number','Hbase'),
('NS','NS_HITS','ADDRESS_MATCH_WEIGHT','Address Match Weight','number','Hbase'),
('NS','UNIFIED_ALERTS','ALERT_DATE','Alert Date','Date','Hbase'),
('NS','UNIFIED_ALERTS','ALERT_ID','Alert Id','text','Hbase'),
('NS','UNIFIED_ALERTS','ALERT_LEVEL','Alert Level','text','Hbase'),
('NS','UNIFIED_ALERTS','ALERT_SCORE','Alert Score','number','Hbase'),
('NS','NS_HITS','BIRTH_COUNTRY_MATCH_SCORE','Birth Country Match Score','number','Hbase'),
('NS','NS_HITS','BIRTH_COUNTRY_MATCH_WEIGHT','Birth Country Match Weigth','number','Hbase'),
('NS','NS_HITS','DOB_MATCH_SCORE','Dob Match Score','number','Hbase'),
('NS','NS_HITS','DOB_MATCH_WEIGHT','Dob Match Weigth','number','Hbase'),
('NS','NS_HITS','FURTHER_INFORMATION','Further Information','text','Hbase'),
('NS','NS_HITS','GENDER_MATCH_SCORE','Gender Match Score','number','Hbase'),
('NS','NS_HITS','GENDER_MATCH_WEIGHT','Gender Match Weight','number','Hbase'),
('NS','NS_HITS','HIT_LEVEL','Hit Level','text','Hbase'),
('NS','NS_HITS','HIT_SCORE','Hit Score','number','Hbase'),
('NS','UNIFIED_ALERTS','HITS_SUMMARY','Hits Summary','text','Hbase'),
('NS','UNIFIED_ALERTS','IS_WHITELISTED','Is WhiteListed','boolean','Hbase'),
('NS','NS_HITS','NAME_ALIAS_MATCH_SCORE','Name Alias Match Score','number','Hbase'),
('NS','NS_HITS','NAME_ALIAS_MATCH_WEIGHT','Name Alias Match Weight','number','Hbase'),
('NS','NS_HITS','NAME_NAME_MATCH_SCORE','Name Name Match Score','number','Hbase'),
('NS','NS_HITS','NAME_NAME_MATCH_WEIGHT','Name Name Match Weight','number','Hbase'),
('NS','NS_HITS','NATIONALITY_MATCH_SCORE','Nationality Match Score','number','Hbase'),
('NS','NS_HITS','NATIONALITY_MATCH_WEIGHT','Nationality Match Weight','number','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ADDRESS','Party Address','text','Hbase'),
('NS','NS_HITS','WATCHLIST_COUNTRY_OF_RESIDENCE','Watchlist Country Of Residence','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ALIASES','Party Aliases','text','Hbase'),,
('NS','NS_HITS','WATCHLIST_COUNTRY_OF_BIRTH','WatchList Country Of Birth','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_BUSINESS_TYPE','Party Business Type','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_CRS_RISK_SCORE','Party Crs Risk Score','number','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_DOB','Party Dob','date','Hbase'),
('NS','NS_HITS','DOB_WATCHLIST','Dob WatchList','date','Hbase'),
('NS','NS_HITS','WATCHLIST_GENDER','WatchList Gender','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ID','Party Id','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ID_COUNTRY','Party Id Country','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ID_NO','Party Id No','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ID_TYPE','Party Id Type','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_NAME','Party Name','text','Hbase'),
('NS','NS_HITS','WATCHLIST_NAME','Watchlist Name','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_NATIONALITY','Party nationality','text','Hbase'),
('NS','NS_HITS','WATCHLIST_NATIONALITY','Watchlist Nationality','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ORG_UNIT','Party Org unit','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_RESIDENCE_COUNTRY','Party Residence Country','text','Hbase'),
('NS','NS_HITS','PARTY_SEGMENT','Party Segment','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_TYPE','Party Type','text','Hbase'),
('NS','UNIFIED_ALERTS','PRIMARY_PARTY_KEY','Primary Party Key','text','Hbase'),
('NS','UNIFIED_ALERTS','PRIMARY_PARTY_NAME','Primary Party Name','text','Hbase'),
('NS','NS_HITS','REVIEW_FEEDBACK','Review Feedback','number','Hbase'),
('NS','UNIFIED_ALERTS','RUN_INSTANCE_EXECUTION_ID','Run Instance Execution Id','text','Hbase'),
('NS','CRS_IAD_MODEL_THRESHOLD ','RUN_INSTANCE_ID','Run Instance Id','number','Hbase'),,
('NS','UNIFIED_ALERTS','SEGMENT_NAME','Segment Name','text','Hbase'),
('NS','NS_HITS','TYPE_OF_HIT','Type Of Hit','text','Hbase'),
('NS','NS_HITS','WATCHLIST_CATEGORY','Watchlist Category','text','Hbase'),
('NS','NS_HITS','WATCHLIST_ID','WatchList Id','text','Hbase'),
('NS','NS_HITS','WATCHLIST_SUB_CATEGORY','Watchlist Sub Category','text','Hbase');







Insert into disp_common_fields 
(product_name,table_name,field_name,field_label,field_type,source_db) Values
('TS','TRANSACTIONS','ADDITIONAL_INFO','Additional Info','text','Hbase'),
('TS','UNIFIED_ALERTS','ALERT_DATE','Alert Date','Date','Hbase'),
('TS','UNIFIED_ALERTS','ALERT_ID','Alert Id','text','Hbase'),
('TS','UNIFIED_ALERTS','ALERT_LEVEL','Alert Level','text','Hbase'),
('TS','UNIFIED_ALERTS','ALERT_SCORE','Alert Score','number','Hbase'),
('TS','NS_HITS','BIRTH_COUNTRY_MATCH_SCORE','Birth Country Match Score','number','Hbase'),
('TS','NS_HITS','BIRTH_COUNTRY_MATCH_WEIGHT','Birth Country Match Weight','number','Hbase'),
('TS','NS_HITS','DOB_MATCH_SCORE','Dob Match Score','number','Hbase'),
('TS','NS_HITS','DOB_MATCH_WEIGHT','Dob Match Weight','number','Hbase'),
('TS','ALERTED_CUSTOMERS','ENTITY_AMOUNT','Entity Amount','number','Hbase'),
('TS','UNIFIED_ALERTS','ENTITY_COUNT','Entity Count','number','Hbase'),
('TS','ALERTED_CUSTOMERS','ENTITY_CURRENCY','Entity Currency','text','Hbase'),
('TS','ALERTED_CUSTOMERS','ENTITY_ROLE','Entity Role','text','Hbase'),
('TS','NS_HITS','FURTHER_INFORMATION','Further Information','text','Hbase'),
('TS','NS_HITS','GENDER_MATCH_SCORE','Gender Match Score','number','Hbase'),
('TS','NS_HITS','GENDER_MATCH_WEIGHT','Gender Match Weight','number','Hbase'),
('TS','NS_HITS','HIT_LEVEL','Hit Level','text','Hbase'),
('TS','NS_HITS','HIT_LEVEL','Hit Level','text','Hbase'),
('TS','UNIFIED_ALERTS','HITS_SUMMARY','Hits Summary','text','Hbase'),
('TS','UNIFIED_ALERTS','IS_WHITELISTED','Is Whitelisted','boolean','Hbase'),
('TS','NS_HITS','NAME_ALIAS_MATCH_SCORE','Name Alias Match Score','number','Hbase'),
('TS','NS_HITS','NAME_ALIAS_MATCH_WEIGHT','Name Alias Match Weight','number','Hbase'),
('TS','NS_HITS','NAME_NAME_MATCH_SCORE','Name Name Match Score','number','Hbase'),
('TS','NS_HITS','NAME_NAME_MATCH_WEIGHT','Name Name Match Weight','number','Hbase'),
('TS','NS_HITS','NATIONALITY_MATCH_SCORE','NationLity Match Score','number','Hbase'),
('TS','NS_HITS','NATIONALITY_MATCH_WEIGHT','Nationality Match Weight','number','Hbase'),
('TS','UNIFIED_ALERTS','OPP_ACCOUNT_NO','Opp Account NO','text','Hbase'),
('TS','UNIFIED_ALERTS','OPP_CURRENCY_CODE','Opp Currency Code','text','Hbase'),
('TS','TRANSACTIONS','OPP_ACCOUNT_NUMBER','Opp Account Number','text','Hbase'),
('TS','UNIFIED_ALERTS','ORIG_CURRENCY_CODE','Orig Currency Code','text','Hbase'),
('TS','UNIFIED_ALERTS','ORIG_TXN_AMOUNT','Orig Txn Amount','number','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_ADDRESS','Party Address','text','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_ALIASES','Party Aliases','text','Hbase'),
('TS','NS_HITS','WATCHLIST_COUNTRY_OF_BIRTH','WatchList Country Of Birth','text','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_BUSINESS_TYPE','Party Business Type','text','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_CRS_RISK_SCORE','Party Crs Risk Score','number','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_DOB','Party Dob','date','Hbase'),
('TS','NS_HITS','DOB_WATCHLIST','Dob WatchList','date','Hbase'),
('TS','NS_HITS','WATCHLIST_GENDER','WatchList Gender','text','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_ID','Party Id','text','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_ID_COUNTRY','Party Id Country','text','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_ID_NO','Party Id No','text','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_ID_TYPE','Party Id Type','text','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_NAME','Party Name','text','Hbase'),
('TS','NS_HITS','WATCHLIST_NAME','Watchlist Name','text','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_NATIONALITY','Party Nationality','text','Hbase'),
('TS','NS_HITS','WATCHLIST_NATIONALITY','Watchlist Nationality','text','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_ORG_UNIT','Party Org Unit','text','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_RESIDENCE_COUNTRY','Party Residence Country','text','Hbase'),
('TS','NS_HITS','PARTY_SEGMENT','Party Segment','text','Hbase'),
('TS','UNIFIED_ALERTS','PARTY_TYPE','Party Type','text','Hbase'),
('TS','UNIFIED_ALERTS','REFERENCE_NUMBER','Reference Number','text','Hbase'),
('TS','NS_HITS','REVIEW_FEEDBACK','Review FeedBack','number','Hbase'),
('TS','UNIFIED_ALERTS','RUN_INSTANCE_EXECUTION_ID','Run Instance Execution Id','text','Hbase'),
('TS','CRS_TM_IAD_MODEL_THRESHOLD','RUN_INSTANCE_ID','Run Instance Id','number','Hbase'),
('TS','UNIFIED_ALERTS','SEGMENT_NAME','Segment Name','text','Hbase'),
('TS','UNIFIED_ALERTS','SOURCE_OF_FUNDS','Source Of Funds','text','Hbase'),
('TS','UNIFIED_ALERTS','SWIFT_MSG_TYPE','Swift Msg Type','text','Hbase'),
('TS','UNIFIED_ALERTS','TRANSACTION_KEY','Transaction Key','text','Hbase'),
('TS','UNIFIED_ALERTS','TXN_DATE_TIME','Txn Date Time','Date','Hbase'),
('TS','UNIFIED_ALERTS','TXN_DIRECTION','Txn Direction','text','Hbase'),
('TS','NS_HITS','TYPE_OF_HIT','Type Of Hit','text','Hbase'),
('TS','NS_HITS','WATCHLIST_CATEGORY','Watchlist Category','text','Hbase'),
('TS','NS_HITS','WATCHLIST_ID','Watchlist Id','text','Hbase'),
('TS','NS_HITS','WATCHLIST_SUB_CATEGORY','Watchlist Sub Category','text','Hbase');
('TS','NS_HITS','ADDRESS_MATCH_SCORE','Address Match Score','number','Hbase'),
('TS','NS_HITS','ADDRESS_MATCH_WEIGHT','Address Match Weigth','number','Hbase'),
('TS','NS_HITS','WATCHLIST_COUNTRY_OF_RESIDENCE','Watchlist Country Of Residence','text','Hbase');





Insert into disp_common_fields 
(product_name,table_name,field_name,field_label,field_type,source_db) Values
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_CLOSED_DATE','Account Closed Date','Date','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_CR_AVG_BALANCE','Account Cr Avg Balance','text','Hbase'),
('FRAML-D','CDD_ALERTS','ACCOUNT_CURRENCY','Account Currency','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_DR_AVG_BALANCE','Account Dr Avg Balance','number','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS ','ACCOUNT_ID','Account Id','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_NAME','Account Name','text','Hbase'),
('FRAML-D','CDD_ALERTS','ACCOUNT_OPEN_DATE','Account Open Date','Date','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_STATUS','Account Status','text','Hbase'),
('FRAML-D','CDD_ALERTS','ACCOUNT_TYPE','Account Type','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','ADVANCE_PAYMENT_AMOUNT','Advance Payment Amount','number','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','ADVANCE_PAYMENT_COUNT','Advance Payment Count','number','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','ADVERSE_NEWS_FLAG','Adverse News Flag','boolean','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','AGE','Age','number','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ALERT_DATE','Alert Date','Date','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ALERT_ID','Alert Id','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ALERT_LEVEL','Alert Level','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ALERT_SCORE','Alert Score','number','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ALERT_STATUS','Alert Status','number','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ALERT_TYPE','Alert Type','number','Hbase'),
('FRAML-D','TRANSACTIONS','AMOUNT','Amount','number','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ANALYST_NAME','Analyst Name','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','ANNUAL_REVENUE_OR_INCOME','Annual Revenue Or Income','number','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','ANNUAL_TURNOVER','Annual Turnover','number','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','ASSET_NAME','Asset Name','text','Hbase'),
('FRAML-D','TRANSACTIONS','ATM_ID','Atm Id','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','BALANCE','Balance','number','Hbase'),
('FRAML-D','TRANSACTIONS','BANK_BRANCH_CODE','Bank Branch Code','text','Hbase'),
('FRAML-D','TRANSACTIONS','BANK_INFO','Bank Info','text','Hbase'),
('FRAML-D','TRANSACTIONS','BENEFICIARY','Beneficiary','text','Hbase'),
('FRAML-D','TRANSACTIONS','BENEFICIARY_BANK_COUNTRY_CODE','Beneficiary Bank Country Code','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','BIRTH_INCORPORATION_COUNTRY','Birth Incorporation Country','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','C2A_RELATIONSHIP','C2a Relationship','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','CITIZENSHIP_COUNTRY','Citizenship Country','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','CLOSURE_DATE','Closure Date','Date','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','CONTACT_NUMBER','Contact Number','text','Hbase'),
('FRAML-D','TRANSACTIONS','COUNTER_PARTY','Counter Party','text','Hbase'),
('FRAML-D','TRANSACTIONS','COUNTER_PARTY_NATIONALITY','Counter Party Nationality','text','Hbase'),
('FRAML-D','TRANSACTIONS','COUNTER_PARTY_TYPE','Counter Party Type','text','Hbase'),
('FRAML-D','TRANSACTIONS','COUNTRY_OF_TRANSACTION','Country Of Transaction','text','Hbase'),
('FRAML-D','TRANSACTIONS','CREDIT_CARD_NUMBER','Credit card Number','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','CREDIT_LIMIT','Credit Limit','number','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','CUSTOMER_TYPE','Customer Type','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','DESIGNATION','Designation','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','DIVISION','Division','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','DOB_OR_INCORPORATION_DATE','Dob Or Incorporation Date','Date','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','DOCUMENT_ID','Document Id','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','DOCUMENT_ISSUE_COUNTRY','Document Issue Country','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','DOCUMENT_TYPE','Document Type','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','EMPLOYER_NAME','Employer Name','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','EMPLOYER_TYPE_OF_BUSINESS','Employer Type Of Business','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS ','EXPECTED_CLOSE_DATE','Expected Close Date','Date','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','GENDER','Gender','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ID_EXPIRY_DATE','Id Expiry Date','Date','Hbase'),
('FRAML-D','UNIFIED_ALERTS','INVESTIGATION_RESULT','Investigation Result','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','INVESTIGATION_RESULT','Investigation Result','text','Hbase'),
('FRAML-D','TRANSACTIONS','IP_RISKINESS','Ip Riskiness','text','Hbase'),
('FRAML-D','TRANSACTIONS','IS_CREDIT','Is Credit','boolean','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','IS_PEP','Is Pep','boolean','Hbase'),
('FRAML-D','UNIFIED_ALERTS','IS_STAFF','Is Staff','boolean','Hbase'),
('FRAML-D','UNIFIED_ALERTS','IS_STR','Is Str','boolean','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_AMOUNT','Loan Amount','number','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_CURRENCY_CODE','Loan Currency Code','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_FIRST_DISBURSEMENT_DATE','Loan First Disbursement Date','Date','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_INSTALLMENT_VALUE','Loan Installment Value','number','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_INSTALLMENT_VALUE','Loan Installment Value','number','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_KEY','Loan Key','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_PURPOSE_CODE','Loan Purpose Code','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_REPAYMENT_STRUCTURE','Loan Repatment Structure','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_STRUCTURE','Loan Structure','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_TYPE','Loan Type','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_TYPE_CODE','Loan type Code','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_CURRENCY_CODE','Loan Current Code','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','NAME_OF_THE_OWNER_OF_THE_ASSET','Name Of The Owner Of The Asset','text','Hbase'),
('FRAML-D','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','NATIONALITY','Nationality','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','NUMBER_OF_PAYMENTS','Number Of Payments','number','Hbase'),
('FRAML-D','UNIFIED_ALERTS','OCCUPATION','Occupation','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','OPP_ACCOUNT_NO','Opp Account No','text','Hbase'),
('FRAML-D','TRANSACTIONS','OUR_REFERENCE','Our Reference','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','PARTY_KEY','party Key','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','PRIMARY_PARTY_KEY','Primary Party Key','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','PRIMARY_PARTY_NAME','Primary Party Name','text','Hbase'),
('FRAML-D','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','RELATION_DESCRIPTION','Relation Description','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS','RESIDENTIAL_ADDRESS','Residential Address','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS','RESIDENCE_OPERATION_COUNTRY','Residence Operation Country','text','Hbase'),
('FRAML-D','CDD_ALERTS','RULES','Rules','text','Hbase'),
('FRAML-D','CRS_CUSTOMER_HISTORY','SEGMENT_NAME','Segment Name','text','Hbase'),
('FRAML-D','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','SHAREHOLDER_PERCENTAGE','Shareholder Percentage','text','Hbase'),
('FRAML-D','TRANSACTIONS','TD_NUMBER','Td Number','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','TOTAL_REPAYMENT_AMOUNT','Total Repayment Amount','number','Hbase'),
('FRAML-D','TRANSACTIONS','TRANCHE_NO','Tranche No','text','Hbase'),
('FRAML-D','TRANSACTIONS','TRANSACTION_CURRENCY','Transaction Currency','text','Hbase'),
('FRAML-D','TRANSACTIONS','TRANSACTION_CURRENCY_AMOUNT','Transaction Currency Amount','number','Hbase'),
('FRAML-D','TRANSACTIONS','TRANSACTION_DATE','Transaction Date','Date','Hbase'),
('FRAML-D','TRANSACTIONS','TRANSACTION_PURPOSE','Transaction Purpose','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','TRANSACTION_TYPE_CODE','Transaction Type Code','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','TRANSACTION_TYPE_DESCRIPTION','Transaction Type Description','text','Hbase'),
('FRAML-D','TRANSACTIONS','YOUR_REFERENCE','Your reference','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','CARD_NUMBER','Card Number','text','Hbase'),
('FRAML-D','TRANSACTIONS','CHEQUE_NO','Cheque No','text','Hbase'),
('FRAML-D','TRANSACTIONS','ID','Id','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_LINKED_CUSTOMERS','LINKED_PARTY_KEY','Linked Party Key','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_CURRENCY_CODE','Loan Currency Code','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','LOAN_GL_GROUP','Loan Gl Group','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','LOAN_GROUP','Loan Group','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','LOAN_MATURITY_DATE','Loan Maturity Date','Date','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','NATURE_OF_THE_ASSET','Nature Of The Asset','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','NEXT_INSTALLMENT_DATE','Next Installment Date','Date','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','NUMBER_OF_REPAYMENTS','Number Of Repayments','number','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','OPEN_DATE','Open Date','Date','Hbase'),
('FRAML-D','UNIFIED_ALERTS','OPP_ACCOUNT_NO','Opp Account No','text','Hbase'),
('FRAML-D','TRANSACTIONS','ORIGINATOR_BANK_COUNTRY_CODE','Originator Bank Country Code','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','OUTSTANDING_LOAN_BALANCE','Outstanding Loan Balance','number','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_LINKED_CUSTOMERS','PARTY_NAME','Party Name','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS','POSTAL_CODE','Postal Code','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS','RESIDENCE_OPERATION_COUNTRY','Residence Operation Country','text','Hbase'),
('FRAML-D','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','SEGMENT','Segment','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','TOTAL_REPAYMENT_AMOUNT','Total Repayment amount','number','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','SPECIAL_ATTENTION_FLAG','Special Attention Flag','boolean','Hbase'),
('FRAML-D','TRANSACTIONS','TELLER_ID','Teller Id','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','TOTAL_REPAID_AMOUNT','Total Repaid Amount','number','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','TOTAL_REPAYMENT_AMOUNT','Total Repayment Amount','number','Hbase');




Insert into disp_common_fields 
(product_name,table_name,field_name,field_label,field_type,source_db) Values
('FRAML-P','UNIFIED_ALERTS','ADDITIONAL_INFO','Additional Info','text','Hbase'),
('FRAML-P','UNIFIED_ALERTS','SOURCE_OF_FUNDS','Source Of Funds','text','Hbase'),
('FRAML-P','UNIFIED_ALERTS','TXN_DATE_TIME','Txn Date Time','Date','Hbase');





Insert into disp_common_fields 
(product_name,table_name,field_name,field_label,field_type,source_db) Values
('TM-SAM','CDD_ALERTS','ACCOUNT_CURRENCY','Account Currency','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','ACCOUNT_ID','Account Id','text','Hbase'),
('TM-SAM','CDD_ALERTS','ACCOUNT_OPEN_DATE','Account Open Date','text','Hbase'),
('TM-SAM','CDD_ALERTS','ACCOUNT_TYPE','Account Type','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','ALERT_DATE','Alert Date','Date','Hbase'),
('TM-SAM','UNIFIED_ALERTS','ALERT_ID','Alert Id','text','Hbase'),
('TM-SAM','UNIFIED_ALERT','ALERT_STATUS','Alert Status','number','Hbase'),
('TM-SAM','UNIFIED_ALERT','BUSINESS_SEGMENT','Business Segment','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','IS_STR','Is Str','boolean','Hbase'),
('TM-SAM','UNIFIED_ALERT','PRIMARY_PARTY_KEY','Primary Party Key','text','Hbase'),
('TM-SAM','TRIGGERED_TRANSACTIONS','TRIGGERED_RULES','Triggered Rules','text','Hbase'),
('TM-SAM','TRIGGERED_TRANSACTIONS','TRIGGERED_TYPOLOGY','Triggered Typology','text','Hbase'),
('TM-SAM','RISK_INDICATORS','RISK_INDICATOR_NAME','risk Indication Name','text','Hbase'),
('TM-SAM','TRANSACTIONS','AMOUNT','Amount','number','Hbase'),
('TM-SAM','TRANSACTIONS','BANK_INFO','Bank Info','text','Hbase'),
('TM-SAM','TRANSACTIONS','BENEFICIARY','Beneficiary','text','Hbase'),
('TM-SAM','TRANSACTIONS','BENEFICIARY_ADDRESS','Beneficiary Address','text','Hbase'),
('TM-SAM','TRANSACTIONS','BENEFICIARY_BANK_COUNTRY_CODE','Beneficiary Bank Country Code','text','Hbase'),
('TM-SAM','TRANSACTIONS','COUNTRY_OF_TRANSACTION','Country Of Transaction','text','Hbase'),
('TM-SAM','TRANSACTIONS','CREDIT_CARD_NUMBER','Credit Card Number','text','Hbase'),
('TM-SAM','TRANSACTIONS','HIGH_RISK_COUNTRY_FLAG','High Risk Country Flag','boolean','Hbase'),
('TM-SAM','TRANSACTIONS','IS_CREDIT','Is Credit','boolean','Hbase'),
('TM-SAM','LOAN_CUSTOMERS','LOAN_CURRENCY_CODE','Loan Currency Code','text','Hbase'),
('TM-SAM','TRANSACTIONS','ORIGINATOR','Originator','text','Hbase'),
('TM-SAM','TRANSACTIONS','ORIGINATOR_ADDRESS','Originator Address','text','Hbase'),
('TM-SAM','TRANSACTIONS','ORIGINATOR_BANK_COUNTRY_CODE','Originator Bank Country Code ','text','Hbase'),
('TM-SAM','LOAN_CUSTOMERS','PARTY_KEY','Party Key','text','Hbase'),
('TM-SAM','TRANSACTIONS','TRANSACTION_CURRENCY','Transaction Currency','text','Hbase'),
('TM-SAM','TRANSACTIONS','TRANSACTION_CURRENCY_AMOUNT','Transaction Currency Amount','number','Hbase'),
('TM-SAM','TRANSACTIONS','TRANSACTION_DATE','Transaction Date','Date','Hbase'),
('TM-SAM','UNIFIED_ALERTS','TRANSACTION_TYPE_CODE','Transaction Type Code','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','TRANSACTION_TYPE_DESCRIPTION','Transaction Type Description','text','Hbase'),)
('TM-SAM','CODES','CODE_TYPE','Code Type','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','ALERT_SOURCE_ID','Alert Source Id','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','ANALYST_FULL_NAME','Analyst Full Name','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','REFERENCE_DATE','Reference Date','Date','Hbase'),
('TM-SAM','UNIFIED_ALERTS','RULES','Rules','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','MODEL_ID','Model Id','number','Hbase'),
('TM-SAM','RISK_INDICATORS','RISK_INDICATOR_ID','Risk Indicator Id','number','Hbase'),
('TM-SAM','TRANSACTIONS','REMITTANCE_COUNTRY','Remittance Country','text','Hbase'),
('TM-SAM','CODES','CODE','Code','text','Hbase'),
('TM-SAM','TRANSACTIONS','ID','Id','text','Hbase');
