Insert into disp_common_fields 
(product_name,table_name,field_name,field_label,field_type,source_db) Values
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_CLOSED_DATE','Account Closed Date','date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_CR_AVG_BALANCE','Account Cr Avg Balance','number','Hbase'),
('CRS','UNIFIED_ALERTS','ACCOUNT_CURRENCY','Account Currency','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_DESCRIPTION','Account Description','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_DR_AVG_BALANCE','Account Dr Avg Balance','number','Hbase'),
('CRS','UNIFIED_ALERTS','ACCOUNT_ID','Account Id','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_NAME','Account Name','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_STATUS','Account Status','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ACQUISITION_DATE','Acquisition Date','date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ADDITIONAL_ID_CITIZENSHIP','Additional Id Citizenship','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','ADVERSE_NEWS_FLAG','Adverse News Flag','boolean','Hbase'),
('CRS','UNIFIED_ALERTS','ALERT_AGE','Alert Age','text','Hbase'),
('CRS','CRS_CUSTOMERS','ALERT_BU_TYPE','Alert Bu Type','text','Hbase'),
('CRS','UNIFIED_ALERTS','ALERT_DATE','Alert Date','Date','Hbase'),
('CRS','UNIFIED_ALERTS','ALERT_ID','Alert Id','text','Hbase'),
('CRS','UNIFIED_ALERTS','ALERT_LEVEL','Alert Level','text','Hbase'),
('CRS','UNIFIED_ALERTS','ALERT_TYPE','Alert Type','number','Hbase'),
('CRS','CRS_CUSTOMERS','AML_BUSINESS','Aml Business','text','Hbase'),
('CRS','CRS_CUSTOMERS','AML_VIOLATION_ENFORCEMENT_FLAG','Aml Violation Enforcement Flag','boolean','Hbase'),
('CRS','TRANSACTIONS','AMOUNT','Amount','number','Hbase'),
('CRS','ALERTED_CUSTOMERS','ANNUAL_REVENUE_OR_INCOME','Annual Revenue Or Income','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','ANTICIPATED_MONTHLY_VOLUME_MISC','Anticipated Monthly Volume Misc','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','BALANCE','Balance','number','Hbase'),
('CRS','TRANSACTIONS','BANK_INFO','Bank Info','text','Hbase'),
('CRS','TRANSACTIONS','BENEFICIARY','Beneficiary','text','Hbase'),
('CRS','TRANSACTIONS','BENEFICIARY_BANK_COUNTRY_CODE','Beneficiary Bank Country Code','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','C2A_RELATIONSHIP','C2a Relationship','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','CARD_NUMBER','Card Number','text','Hbase'),
('CRS','CRS_CUSTOMERS','CHANNEL','Channel','text','Hbase'),
('CRS','TRANSACTIONS','CHEQUE_NO','Cheque No','text','Hbase'),
('CRS','UNIFIED_ALERTS','CLOSURE_DATE','Closure Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS','COMPLEX_STRUCTURE','Complex Structure','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','CONTACT_NUMBER','Contact Number','text','Hbase'),
('CRS','TRANSACTIONS','COUNTRY_OF_TRANSACTION','Country Of Transaction','text','Hbase'),
('CRS','TRANSACTIONS','CREDIT_CARD_NUMBER','Credit Card Number','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','CREDIT_LIMIT','Credit Limit','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','CURRENCY_CODE','Currency Code','text','Hbase'),
('CRS','CRS_CUSTOMERS','CUSTOMER_INDUSTRY','Customer Industry','text','Hbase'),
('CRS','CRS_CUSTOMERS','CUSTOMER_KEY','Customer Key','text','Hbase'),
('CRS','CRS_CUSTOMERS','CUSTOMER_NAME','Customer Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','CUSTOMER_ONBOARD_DATE','Customer Onboard Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS','CUSTOMER_STATUS','Customer Status','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','CUSTOMER_TYPE','Customer Type','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','DESIGNATION','Designation','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','DIVISION','Division','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','DOB_OR_INCORPORATION_DATE','Dob Or Incorporation Date','Date','Hbase'),
('CRS','ALERTED_CUSTOMERS','DOCUMENT_ID','Document Id','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','DOCUMENT_ISSUE_COUNTRY','Document Issue Country','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','DOCUMENT_TYPE','Document Type','text','Hbase'),
('CRS','CRS_CUSTOMERS','DOMESTIC_PEP_FLAG','Domestic Pep Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS','DOMESTIC_RCA_FLAG','Domestic Rca Flag','boolean','Hbase'),
('CRS','ALERTED_CUSTOMERS','EMPLOYER_NAME','Employer Name','text','Hbase'),
('CRS','CUSTOMER_OCCUPATION_BUSINESS','EMPLOYMENT_BUSINESS_STATUS','Employment Business status','text','Hbase'),
('CRS','CRS_CUSTOMERS','EMPLOYMENT_STATUS','Employment Status','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','ENTITY_TYPE_DESC','Entity Type Desc','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FD_MATURITY_DATE','Fd Maturity Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FD_ORIGINAL_AMOUNT','Fd Original Amount','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FD_PLACEMENT_DATE','Fd Placement Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FD_RECEIPT_NUMBER','Fd Receipt Number','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FD_WITHDRAWAL_DATE','Fd Withdrawal Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FOREIGN_PEP_FLAG','Foreign Pep Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','FOREIGN_RCA_FLAG','Foreign Rca Flag','boolean','Hbase'),
('CRS','ALERTED_CUSTOMERS','GENDER','Gender','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','HIGH_RISK_PARTY_INFO','High Risk Party Info','text','Hbase'),
('CRS','UNIFIED_ALERTS','ID_EXPIRY_DATE','Id Expiry date','Date','Hbase'),
('CRS','CRS_CUSTOMERS','INCOMPLETE_CDD_FLAG','Incomplete Cdd Flag','boolean','Hbase'),
('CRS','TRANSACTIONS','IS_CREDIT','Is Credit','boolean','Hbase'),
('CRS','UNIFIED_ALERTS','IS_STAFF','Is Staff','boolean','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','KYC_DECLARED_MONTHLY_INCOMING_AMOUNT','Kyc Declared Monthly Incoming Amount','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','KYC_DECLARED_MONTHLY_INCOMING_VOL','Kyc Declared Monthly Incoming Vol','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','KYC_DECLARED_MONTHLY_OUTGOING_AMOUNT','Kyc Declared Monthly Outgoing Amount','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','KYC_DECLARED_MONTHLY_OUTGOING_VOL','Kyc Declared Monthly Outgoing Vol','number','Hbase'),
('CRS','ALERTED_CUSTOMERS','KYC_MAILING_ADDRESS','Kyc Mailing Address','text','Hbase'),
('CRS','CRS_CUSTOMERS','KYC_REVIEW_DATE','Kyc Review Date','Date','Hbase'),
('CRS','CRS_CUSTOMER_HISTORY','KYC_RISK_SCORE','Kyc Risk Score','number','Hbase'),
('CRS','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','LINKED_PARTY_KEY','Linked Party Key','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_AMOUNT','Loan Amount','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_DISBURSEMENT_DATE','Loan DisBurseMent Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_GL_GROUP','Loan Gl Group','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_GROUP','Loan Group','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_INSTALLMENT_AMOUNT','Loan Installment Amount','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_MATURITY_DATE','Loan Maturity Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_PURPOSE_CODE','Loan Purpose Code','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','LOAN_TYPE','Loan Type','text','Hbase'),
('CRS','CRS_CUSTOMERS','MARITAL_STATUS','Marital Status','text','Hbase'),
('CRS','CUSTOMER_OCCUPATION_BUSINESS','MAS_INDUSTRY_CODE','Mas Industry Code','text','Hbase'),
('CRS','TRANSACTIONS','MERCHANT_NAME','Merchant Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','NATIONALITY','Nationality','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','NATURE_OF_BUSINESS','Nature Of Business','text','Hbase'),
('CRS','CRS_CUSTOMERS','NON_PHYSICAL_ADDRESS_FLAG','Non Physical Address Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','NUMBER_OF_REPAYMENTS','Number Of Repayments','number','Hbase'),
('CRS','UNIFIED_ALERTS','OCCUPATION','Occupation','text','Hbase'),
('CRS','CUSTOMER_OCCUPATION_BUSINESS','OCCUPATION_BUSINESS','Occupation Business','text','Hbase'),
('CRS','CUSTOMER_OCCUPATION_BUSINESS','OCCUPATION_BUSINESS_END_DATE','Occupation Business End Date','Date','Hbase'),
('CRS','CUSTOMER_OCCUPATION_BUSINESS','OCCUPATION_BUSINESS_START_DATE','Occupation Business Start Date','Date','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','OPEN_DATE','Open Date','Date','Hbase'),
('CRS','TRANSACTIONS','ORIGINATOR','Originator','text','Hbase'),
('CRS','TRANSACTIONS','ORIGINATOR_BANK_COUNTRY_CODE','Originator Bank Country Code','text','Hbase'),
('CRS','TRANSACTIONS','OUR_REFERENCE','Our Reference','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','OUTSTANDING_FD_BALANCE','OutStanding fd balance','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','OUTSTANDING_LOAN_BALANCE','OutStanding Loan balance','number','Hbase'),
('CRS','CRS_CUSTOMER_HISTORY','OVERALL_RISK_SCORE','Overall Risk Score','number','Hbase'),
('CRS','CRS_CUSTOMERS','PAID_UP_CAPITAL','Paid Up Capital','number','Hbase'),
('CRS','CRS_CUSTOMERS','PARENT_HIGH_RISK_FLAG','Parent High Risk Flag','boolean','Hbase'),
('CRS','ALERTED_CUSTOMERS','PARTY_NAME','Party Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','PEP_FLAG','Pep Flag','Boolean','Hbase'),
('CRS','CRS_CUSTOMERS','PEP_IND','Pep Ind','Boolean','Hbase'),
('CRS','UNIFIED_ALERTS','POPULATION_CODE','Population Code','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','POSTAL_CODE','Postal Code','text','Hbase'),
('CRS','UNIFIED_ALERTS','PREDICTION_DATE','Prediction Date','Date','Hbase'),
('CRS','UNIFIED_ALERTS','PRIMARY_PARTY_KEY','Primary Party Key','text','Hbase'),
('CRS','CRS_CUSTOMER_HISTORY','PRODUCT_NAME','Product Name','text','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','PURPOSE_OF_OPENING','Purpose Of Opening','text','Hbase'),
('CRS','CRS_CUSTOMERS','RACE','Race','text','Hbase'),
('CRS','CUSTOMER_OCCUPATION_BUSINESS','REGIONS_OR_COUNTRY_OF_OPERATION','Regions Or Country Of Operation','text','Hbase'),
('CRS','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','RELATION_DESCRIPTION','Relation Description','text','Hbase'),
('CRS','CRS_CUSTOMERS','RELATIONSHIP_MGR_ID','RelationShip Mgr Id','text','Hbase'),
('CRS','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','RELATION_TYPE','Relation Type','text','Hbase'),
('CRS','CRS_CUSTOMERS','RESIDENCE_FLAG','Residence Flag','boolean','Hbase'),
('CRS','ALERTED_CUSTOMERS','RESIDENCE_OPERATION_COUNTRY','Residence Operation Country','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','RESIDENTIAL_ADDRESS','Residential Address','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','RISK_RATING','Risk Rating','text','Hbase'),
('CRS','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','RISK_RATING','Risk Rating','text','Hbase'),
('CRS','CRS_COMPONENT_RISK_SCORE','RISK_SHIFT','Risk Shift','text','Hbase'),
('CRS','CRS_CUSTOMERS','SANCTION_FLAG','Sanction Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS','SECONDARY_AML_BUSINESS','Secondary Aml Business','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','SEGMENT','Segment','text','Hbase'),
('CRS','UNIFIED_ALERTS','SEGMENT_CODE','Segment Code','text','Hbase'),
('CRS','UNIFIED_ALERTS','SEGMENT_NAME','Segment Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SELF_DISCOVERED_PEP_OR_RCA','Self Discovered Pep Or Rca','boolean','Hbase'),
('CRS','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','SHAREHOLDER_PERCENTAGE','ShareHolder Percentage','text','Hbase'),
('CRS','CRS_CUSTOMERS','SHAREHOLDER_BO_OUTSIDE_FLAG','Shareholder Bo Outside Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS','SINGLE_ACCT_OPERATE_FLAG','Single Acct Operate Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS','SOF_3RD_PARTY_CHEQUE_PROVIDER_NAME','Sof 3rd Party Cheque Provider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOF_3RD_PARTY_INTERNET_BANK_OR_INTERNAL_TRF_PROVIDER_NAME','Sof 3rd Party Internet Bank Or  Internal Trf Provider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOF_3RD_PARTY_REMITTANCE_PROVIDER_NAME','Sof 3rd Party Remittance ProVider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOF_CASH_CASH_CHEQUE_PROVIDER_NAME','Sof Cash Cash Cheque Provider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOF_NON_CASH_CHEQUE_CASHIER_ORDER_BANK_DRAFT_PROVIDER_NAME','Sof Non Cash Cheque Cashier Order Bank Draft Provider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOF_SAME_PARTY_INTERNET_BANK_OR_INTERNAL_TRF_PROVIDER_NAME','Sof Same Party Internet Bank Or Internal Trf Provider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOLE_DIRECTOR_FLAG','Sole Director Flag','boolean','Hbase'),
('CRS','UNIFIED_ALERTS','SOURCE_OF_FUNDS','Source Of Funds','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOW_BUSINESS_OWNERSHIP_COMPANY_NAME','Sow Business OwnerShip Company Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOW_EMPLOYER_NAME','Sow Employer Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOW_INHERITANCE_GIFTS_PROVIDER_NAME','Sow Inheritance Gifts Provider Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOW_INVESTMENT_TYPE','Sow Investment Type','text','Hbase'),
('CRS','CRS_CUSTOMERS','SOW_RENTAL_RECEIPT_PROPERTY_TYPE','Sow Rental Receipt Property Type','text','Hbase'),
('CRS','CRS_CUSTOMERS','STATUS_CODE','Status Code','text','Hbase'),
('CRS','CRS_CUSTOMERS','STOCK_EXCHANGE_LIST','Stock Exchange List','text','Hbase'),
('CRS','CRS_CUSTOMER_HISTORY','STR_COUNT','Str Count','number','Hbase'),
('CRS','CRS_CUSTOMERS','TAX_HAVEN_FLAG','Tax Haven Flag','boolean','Hbase'),
('CRS','TRANSACTIONS','TELLER_ID','Teller Id','text','Hbase'),
('CRS','CRS_CUSTOMERS','TOTAL_AUM','Total Aum','number','Hbase'),
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','TOTAL_REPAID_AMOUNT','Total Repaid Amount','number','Hbase'),
('CRS','CRS_CUSTOMERS','TPT_CORE_PARTICIPANT_TO_LOAN_NAME','Tpt Core Participant To Loan Name','text','Hbase'),
('CRS','CRS_CUSTOMERS','TPT_MAJOR_BUYER_NAME','Tpt Major Buyer Name','text','Hbase')
('CRS','CRS_CUSTOMERS','TPT_MAJOR_SUPPLIER_NAME','Tpt Major Supplier Name','text','Hbase')
('CRS','TRANSACTIONS','TRANCHE_NO','Tranche No','text','Hbase')
('CRS','TRANSACTIONS','TRANSACTION_CURRENCY','Transaction Currency','text','Hbase')
('CRS','TRANSACTIONS','TRANSACTION_CURRENCY_AMOUNT','Transaction Currency Amount','number','Hbase')
('CRS','TRANSACTIONS','TRANSACTION_DATE','Transaction Date','Date','Hbase')
('CRS','TRANSACTIONS','TRANSACTION_TYPE_CODE','Transaction Type Code','text','Hbase')
('CRS','TRANSACTIONS','TRANSACTION_TYPE_DESCRIPTION','Transaction Type Description','text','Hbase')
('CRS','CRS_CUSTOMERS_TO_ACCOUNTS','TYPE_CODE','Type Code','text','Hbase'),
('CRS','CRS_CUSTOMERS','UNDERLYING_BUZ_TAX_FLAG','Underlying Buz Tax Flag','boolean','Hbase'),
('CRS','CRS_CUSTOMERS','WHOLESALE_BANKNOTE_FLAG','Wholesale Banknote Flag','boolean','Hbase'),
('CRS','TRANSACTIONS','YOUR_REFERENCE','Your Reference','text','Hbase'),
('CRS','ALERTED_CUSTOMERS','AGE','Age','number','Hbase'),
('CRS','TRANSACTIONS','ID','Id','text','Hbase'),
('CRS','TRANSACTIONS','MCC','Mcc','text','Hbase');




