Insert into disp_common_fields 
(product_name,table_name,field_name,field_label,field_type,source_db) Values
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_CLOSED_DATE','Account Closed Date','Date','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_CR_AVG_BALANCE','Account Cr Avg Balance','text','Hbase'),
('FRAML-D','CDD_ALERTS','ACCOUNT_CURRENCY','Account Currency','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_DR_AVG_BALANCE','Account Dr Avg Balance','number','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS ','ACCOUNT_ID','Account Id','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_NAME','Account Name','text','Hbase'),
('FRAML-D','CDD_ALERTS','ACCOUNT_OPEN_DATE','Account Open Date','Date','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','ACCOUNT_STATUS','Account Status','text','Hbase'),
('FRAML-D','CDD_ALERTS','ACCOUNT_TYPE','Account Type','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','ADVANCE_PAYMENT_AMOUNT','Advance Payment Amount','number','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','ADVANCE_PAYMENT_COUNT','Advance Payment Count','number','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','ADVERSE_NEWS_FLAG','Adverse News Flag','boolean','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','AGE','Age','number','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ALERT_DATE','Alert Date','Date','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ALERT_ID','Alert Id','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ALERT_LEVEL','Alert Level','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ALERT_SCORE','Alert Score','number','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ALERT_STATUS','Alert Status','number','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ALERT_TYPE','Alert Type','number','Hbase'),
('FRAML-D','TRANSACTIONS','AMOUNT','Amount','number','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ANALYST_NAME','Analyst Name','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','ANNUAL_REVENUE_OR_INCOME','Annual Revenue Or Income','number','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','ANNUAL_TURNOVER','Annual Turnover','number','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','ASSET_NAME','Asset Name','text','Hbase'),
('FRAML-D','TRANSACTIONS','ATM_ID','Atm Id','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','BALANCE','Balance','number','Hbase'),
('FRAML-D','TRANSACTIONS','BANK_BRANCH_CODE','Bank Branch Code','text','Hbase'),
('FRAML-D','TRANSACTIONS','BANK_INFO','Bank Info','text','Hbase'),
('FRAML-D','TRANSACTIONS','BENEFICIARY','Beneficiary','text','Hbase'),
('FRAML-D','TRANSACTIONS','BENEFICIARY_BANK_COUNTRY_CODE','Beneficiary Bank Country Code','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','BIRTH_INCORPORATION_COUNTRY','Birth Incorporation Country','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','C2A_RELATIONSHIP','C2a Relationship','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','CITIZENSHIP_COUNTRY','Citizenship Country','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','CLOSURE_DATE','Closure Date','Date','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','CONTACT_NUMBER','Contact Number','text','Hbase'),
('FRAML-D','TRANSACTIONS','COUNTER_PARTY','Counter Party','text','Hbase'),
('FRAML-D','TRANSACTIONS','COUNTER_PARTY_NATIONALITY','Counter Party Nationality','text','Hbase'),
('FRAML-D','TRANSACTIONS','COUNTER_PARTY_TYPE','Counter Party Type','text','Hbase'),
('FRAML-D','TRANSACTIONS','COUNTRY_OF_TRANSACTION','Country Of Transaction','text','Hbase'),
('FRAML-D','TRANSACTIONS','CREDIT_CARD_NUMBER','Credit card Number','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','CREDIT_LIMIT','Credit Limit','number','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','CUSTOMER_TYPE','Customer Type','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','DESIGNATION','Designation','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','DIVISION','Division','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','DOB_OR_INCORPORATION_DATE','Dob Or Incorporation Date','Date','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','DOCUMENT_ID','Document Id','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','DOCUMENT_ISSUE_COUNTRY','Document Issue Country','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','DOCUMENT_TYPE','Document Type','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','EMPLOYER_NAME','Employer Name','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','EMPLOYER_TYPE_OF_BUSINESS','Employer Type Of Business','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS ','EXPECTED_CLOSE_DATE','Expected Close Date','Date','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','GENDER','Gender','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','ID_EXPIRY_DATE','Id Expiry Date','Date','Hbase'),
('FRAML-D','UNIFIED_ALERTS','INVESTIGATION_RESULT','Investigation Result','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','INVESTIGATION_RESULT','Investigation Result','text','Hbase'),
('FRAML-D','TRANSACTIONS','IP_RISKINESS','Ip Riskiness','text','Hbase'),
('FRAML-D','TRANSACTIONS','IS_CREDIT','Is Credit','boolean','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','IS_PEP','Is Pep','boolean','Hbase'),
('FRAML-D','UNIFIED_ALERTS','IS_STAFF','Is Staff','boolean','Hbase'),
('FRAML-D','UNIFIED_ALERTS','IS_STR','Is Str','boolean','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_AMOUNT','Loan Amount','number','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_CURRENCY_CODE','Loan Currency Code','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_FIRST_DISBURSEMENT_DATE','Loan First Disbursement Date','Date','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_INSTALLMENT_VALUE','Loan Installment Value','number','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_INSTALLMENT_VALUE','Loan Installment Value','number','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_KEY','Loan Key','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_PURPOSE_CODE','Loan Purpose Code','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_REPAYMENT_STRUCTURE','Loan Repatment Structure','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_STRUCTURE','Loan Structure','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_TYPE','Loan Type','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_TYPE_CODE','Loan type Code','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_CURRENCY_CODE','Loan Current Code','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','NAME_OF_THE_OWNER_OF_THE_ASSET','Name Of The Owner Of The Asset','text','Hbase'),
('FRAML-D','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','NATIONALITY','Nationality','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','NUMBER_OF_PAYMENTS','Number Of Payments','number','Hbase'),
('FRAML-D','UNIFIED_ALERTS','OCCUPATION','Occupation','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','OPP_ACCOUNT_NO','Opp Account No','text','Hbase'),
('FRAML-D','TRANSACTIONS','OUR_REFERENCE','Our Reference','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','PARTY_KEY','party Key','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','PRIMARY_PARTY_KEY','Primary Party Key','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','PRIMARY_PARTY_NAME','Primary Party Name','text','Hbase'),
('FRAML-D','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','RELATION_DESCRIPTION','Relation Description','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS','RESIDENTIAL_ADDRESS','Residential Address','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS','RESIDENCE_OPERATION_COUNTRY','Residence Operation Country','text','Hbase'),
('FRAML-D','CDD_ALERTS','RULES','Rules','text','Hbase'),
('FRAML-D','CRS_CUSTOMER_HISTORY','SEGMENT_NAME','Segment Name','text','Hbase'),
('FRAML-D','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','SHAREHOLDER_PERCENTAGE','Shareholder Percentage','text','Hbase'),
('FRAML-D','TRANSACTIONS','TD_NUMBER','Td Number','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','TOTAL_REPAYMENT_AMOUNT','Total Repayment Amount','number','Hbase'),
('FRAML-D','TRANSACTIONS','TRANCHE_NO','Tranche No','text','Hbase'),
('FRAML-D','TRANSACTIONS','TRANSACTION_CURRENCY','Transaction Currency','text','Hbase'),
('FRAML-D','TRANSACTIONS','TRANSACTION_CURRENCY_AMOUNT','Transaction Currency Amount','number','Hbase'),
('FRAML-D','TRANSACTIONS','TRANSACTION_DATE','Transaction Date','Date','Hbase'),
('FRAML-D','TRANSACTIONS','TRANSACTION_PURPOSE','Transaction Purpose','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','TRANSACTION_TYPE_CODE','Transaction Type Code','text','Hbase'),
('FRAML-D','UNIFIED_ALERTS','TRANSACTION_TYPE_DESCRIPTION','Transaction Type Description','text','Hbase'),
('FRAML-D','TRANSACTIONS','YOUR_REFERENCE','Your reference','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','CARD_NUMBER','Card Number','text','Hbase'),
('FRAML-D','TRANSACTIONS','CHEQUE_NO','Cheque No','text','Hbase'),
('FRAML-D','TRANSACTIONS','ID','Id','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_LINKED_CUSTOMERS','LINKED_PARTY_KEY','Linked Party Key','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','LOAN_CURRENCY_CODE','Loan Currency Code','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','LOAN_GL_GROUP','Loan Gl Group','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','LOAN_GROUP','Loan Group','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','LOAN_MATURITY_DATE','Loan Maturity Date','Date','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','NATURE_OF_THE_ASSET','Nature Of The Asset','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','NEXT_INSTALLMENT_DATE','Next Installment Date','Date','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','NUMBER_OF_REPAYMENTS','Number Of Repayments','number','Hbase'),
('FRAML-D','CRS_CUSTOMERS_TO_ACCOUNTS','OPEN_DATE','Open Date','Date','Hbase'),
('FRAML-D','UNIFIED_ALERTS','OPP_ACCOUNT_NO','Opp Account No','text','Hbase'),
('FRAML-D','TRANSACTIONS','ORIGINATOR_BANK_COUNTRY_CODE','Originator Bank Country Code','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','OUTSTANDING_LOAN_BALANCE','Outstanding Loan Balance','number','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_LINKED_CUSTOMERS','PARTY_NAME','Party Name','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS','POSTAL_CODE','Postal Code','text','Hbase'),
('FRAML-D','CRS_CUSTOMERS','RESIDENCE_OPERATION_COUNTRY','Residence Operation Country','text','Hbase'),
('FRAML-D','CRS_ALERTED_CUSTOMERS_LINKED_CUSTOMERS','SEGMENT','Segment','text','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','TOTAL_REPAYMENT_AMOUNT','Total Repayment amount','number','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS','SPECIAL_ATTENTION_FLAG','Special Attention Flag','boolean','Hbase'),
('FRAML-D','TRANSACTIONS','TELLER_ID','Teller Id','text','Hbase'),
('FRAML-D','ALERTED_CUSTOMERS_TO_ACCOUNTS','TOTAL_REPAID_AMOUNT','Total Repaid Amount','number','Hbase'),
('FRAML-D','LOAN_CUSTOMERS','TOTAL_REPAYMENT_AMOUNT','Total Repayment Amount','number','Hbase');
