Insert into disp_common_fields 
(product_name,table_name,field_name,field_label,field_type,source_db) Values
('NS','UNIFIED_ALERTS','ACCOUNT_ID','Account Id','text','Hbase'),
('NS','UNIFIED_ALERTS','ACCOUNT_TYPE','Account Type','text','Hbase'),
('NS','NS_HITS','ADDRESS_MATCH_SCORE','Address Match Score','number','Hbase'),
('NS','NS_HITS','ADDRESS_MATCH_WEIGHT','Address Match Weight','number','Hbase'),
('NS','UNIFIED_ALERTS','ALERT_DATE','Alert Date','Date','Hbase'),
('NS','UNIFIED_ALERTS','ALERT_ID','Alert Id','text','Hbase'),
('NS','UNIFIED_ALERTS','ALERT_LEVEL','Alert Level','text','Hbase'),
('NS','UNIFIED_ALERTS','ALERT_SCORE','Alert Score','number','Hbase'),
('NS','NS_HITS','BIRTH_COUNTRY_MATCH_SCORE','Birth Country Match Score','number','Hbase'),
('NS','NS_HITS','BIRTH_COUNTRY_MATCH_WEIGHT','Birth Country Match Weigth','number','Hbase'),
('NS','NS_HITS','DOB_MATCH_SCORE','Dob Match Score','number','Hbase'),
('NS','NS_HITS','DOB_MATCH_WEIGHT','Dob Match Weigth','number','Hbase'),
('NS','NS_HITS','FURTHER_INFORMATION','Further Information','text','Hbase'),
('NS','NS_HITS','GENDER_MATCH_SCORE','Gender Match Score','number','Hbase'),
('NS','NS_HITS','GENDER_MATCH_WEIGHT','Gender Match Weight','number','Hbase'),
('NS','NS_HITS','HIT_LEVEL','Hit Level','text','Hbase'),
('NS','NS_HITS','HIT_SCORE','Hit Score','number','Hbase'),
('NS','UNIFIED_ALERTS','HITS_SUMMARY','Hits Summary','text','Hbase'),
('NS','UNIFIED_ALERTS','IS_WHITELISTED','Is WhiteListed','boolean','Hbase'),
('NS','NS_HITS','NAME_ALIAS_MATCH_SCORE','Name Alias Match Score','number','Hbase'),
('NS','NS_HITS','NAME_ALIAS_MATCH_WEIGHT','Name Alias Match Weight','number','Hbase'),
('NS','NS_HITS','NAME_NAME_MATCH_SCORE','Name Name Match Score','number','Hbase'),
('NS','NS_HITS','NAME_NAME_MATCH_WEIGHT','Name Name Match Weight','number','Hbase'),
('NS','NS_HITS','NATIONALITY_MATCH_SCORE','Nationality Match Score','number','Hbase'),
('NS','NS_HITS','NATIONALITY_MATCH_WEIGHT','Nationality Match Weight','number','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ADDRESS','Party Address','text','Hbase'),
('NS','NS_HITS','WATCHLIST_COUNTRY_OF_RESIDENCE','Watchlist Country Of Residence','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ALIASES','Party Aliases','text','Hbase'),,
('NS','NS_HITS','WATCHLIST_COUNTRY_OF_BIRTH','WatchList Country Of Birth','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_BUSINESS_TYPE','Party Business Type','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_CRS_RISK_SCORE','Party Crs Risk Score','number','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_DOB','Party Dob','date','Hbase'),
('NS','NS_HITS','DOB_WATCHLIST','Dob WatchList','date','Hbase'),
('NS','NS_HITS','WATCHLIST_GENDER','WatchList Gender','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ID','Party Id','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ID_COUNTRY','Party Id Country','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ID_NO','Party Id No','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ID_TYPE','Party Id Type','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_NAME','Party Name','text','Hbase'),
('NS','NS_HITS','WATCHLIST_NAME','Watchlist Name','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_NATIONALITY','Party nationality','text','Hbase'),
('NS','NS_ITS','WATCHLIST_NATIONALITY','Watchlist Nationality','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_ORG_UNIT','Party Org unit','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_RESIDENCE_COUNTRY','Party Residence Country','text','Hbase'),
('NS','NS_HITS','PARTY_SEGMENT','Party Segment','text','Hbase'),
('NS','UNIFIED_ALERTS','PARTY_TYPE','Party Type','text','Hbase'),
('NS','UNIFIED_ALERTS','PRIMARY_PARTY_KEY','Primary Party Key','text','Hbase'),
('NS','UNIFIED_ALERTS','PRIMARY_PARTY_NAME','Primary Party Name','text','Hbase'),
('NS','NS_HITS','REVIEW_FEEDBACK','Review Feedback','number','Hbase'),
('NS','UNIFIED_ALERTS','RUN_INSTANCE_EXECUTION_ID','Run Instance Execution Id','text','Hbase'),
('NS','CRS_IAD_MODEL_THRESHOLD ','RUN_INSTANCE_ID','Run Instance Id','number','Hbase'),,
('NS','UNIFIED_ALERTS','SEGMENT_NAME','Segment Name','text','Hbase'),
('NS','NS_HITS','TYPE_OF_HIT','Type Of Hit','text','Hbase'),
('NS','NS_HITS','WATCHLIST_CATEGORY','Watchlist Category','text','Hbase'),
('NS','NS_HITS','WATCHLIST_ID','WatchList Id','text','Hbase'),
('NS','NS_HITS','WATCHLIST_SUB_CATEGORY','Watchlist Sub Category','text','Hbase');
