Insert into disp_common_fields 
(product_name,table_name,field_name,field_label,field_type,source_db) Values
('TM-SAM','CDD_ALERTS','ACCOUNT_CURRENCY','Account Currency','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','ACCOUNT_ID','Account Id','text','Hbase'),
('TM-SAM','CDD_ALERTS','ACCOUNT_OPEN_DATE','Account Open Date','text','Hbase'),
('TM-SAM','CDD_ALERTS','ACCOUNT_TYPE','Account Type','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','ALERT_DATE','Alert Date','Date','Hbase'),
('TM-SAM','UNIFIED_ALERTS','ALERT_ID','Alert Id','text','Hbase'),
('TM-SAM','UNIFIED_ALERT','ALERT_STATUS','Alert Status','number','Hbase'),
('TM-SAM','UNIFIED_ALERT','BUSINESS_SEGMENT','Business Segment','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','IS_STR','Is Str','boolean','Hbase'),
('TM-SAM','UNIFIED_ALERT','PRIMARY_PARTY_KEY','Primary Party Key','text','Hbase'),
('TM-SAM','TRIGGERED_TRANSACTIONS','TRIGGERED_RULES','Triggered Rules','text','Hbase'),
('TM-SAM','TRIGGERED_TRANSACTIONS','TRIGGERED_TYPOLOGY','Triggered Typology','text','Hbase'),
('TM-SAM','RISK_INDICATORS','RISK_INDICATOR_NAME','risk Indication Name','text','Hbase'),
('TM-SAM','TRANSACTIONS','AMOUNT','Amount','number','Hbase'),
('TM-SAM','TRANSACTIONS','BANK_INFO','Bank Info','text','Hbase'),
('TM-SAM','TRANSACTIONS','BENEFICIARY','Beneficiary','text','Hbase'),
('TM-SAM','TRANSACTIONS','BENEFICIARY_ADDRESS','Beneficiary Address','text','Hbase'),
('TM-SAM','TRANSACTIONS','BENEFICIARY_BANK_COUNTRY_CODE','Beneficiary Bank Country Code','text','Hbase'),
('TM-SAM','TRANSACTIONS','COUNTRY_OF_TRANSACTION','Country Of Transaction','text','Hbase'),
('TM-SAM','TRANSACTIONS','CREDIT_CARD_NUMBER','Credit Card Number','text','Hbase'),
('TM-SAM','TRANSACTIONS','HIGH_RISK_COUNTRY_FLAG','High Risk Country Flag','boolean','Hbase'),
('TM-SAM','TRANSACTIONS','IS_CREDIT','Is Credit','boolean','Hbase'),
('TM-SAM','LOAN_CUSTOMERS','LOAN_CURRENCY_CODE','Loan Currency Code','text','Hbase'),
('TM-SAM','TRANSACTIONS','ORIGINATOR','Originator','text','Hbase'),
('TM-SAM','TRANSACTIONS','ORIGINATOR_ADDRESS','Originator Address','text','Hbase'),
('TM-SAM','TRANSACTIONS','ORIGINATOR_BANK_COUNTRY_CODE','Originator Bank Country Code ','text','Hbase'),
('TM-SAM','LOAN_CUSTOMERS','PARTY_KEY','Party Key','text','Hbase'),
('TM-SAM','TRANSACTIONS','TRANSACTION_CURRENCY','Transaction Currency','text','Hbase'),
('TM-SAM','TRANSACTIONS','TRANSACTION_CURRENCY_AMOUNT','Transaction Currency Amount','number','Hbase'),
('TM-SAM','TRANSACTIONS','TRANSACTION_DATE','Transaction Date','Date','Hbase'),
('TM-SAM','UNIFIED_ALERTS','TRANSACTION_TYPE_CODE','Transaction Type Code','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','TRANSACTION_TYPE_DESCRIPTION','Transaction Type Description','text','Hbase'),)
('TM-SAM','CODES','CODE_TYPE','Code Type','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','ALERT_SOURCE_ID','Alert Source Id','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','ANALYST_FULL_NAME','Analyst Full Name','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','REFERENCE_DATE','Reference Date','Date','Hbase'),
('TM-SAM','UNIFIED_ALERTS','RULES','Rules','text','Hbase'),
('TM-SAM','UNIFIED_ALERTS','MODEL_ID','Model Id','number','Hbase'),
('TM-SAM','RISK_INDICATORS','RISK_INDICATOR_ID','Risk Indicator Id','number','Hbase'),
('TM-SAM','TRANSACTIONS','REMITTANCE_COUNTRY','Remittance Country','text','Hbase'),
('TM-SAM','CODES','CODE','Code','text','Hbase'),
('TM-SAM','TRANSACTIONS','ID','Id','text','Hbase');
